Creating workspace id in section
copods/kela-quiz pull request #192
Opened 2022-10-04 10:24 UTC by arpita-20

2022-10-06 04:08 UTC, richa-copods requested changes

2022-10-06 04:08 UTC, richa-copods commented on prisma/migrations/20221004100256_workspace_queries/migration.sql
> +      random_id=gen_random_uuid();
Please rename it to workspaceId

2022-10-06 04:08 UTC, richa-copods commented on prisma/migrations/20221004100256_workspace_queries/migration.sql
> +        userIdVar=userList."id";
No need to create these variables, values can be used directly

2022-10-06 04:08 UTC, richa-copods commented on prisma/schema.prisma
> +  id          String    @id @default(cuid())
As we are using uuid so please update this

2022-10-06 04:08 UTC, richa-copods commented on prisma/schema.prisma
> +  id              String            @id @default(cuid())
We are going ahead with uuid right? Please update this

2022-10-07 07:45 UTC, anuragP04 approved these changes

2022-10-07 07:54 UTC, merged