108 resend member invitation
copods/kela-quiz pull request #193
Opened 2022-10-04 10:30 UTC by NitinCopods

Resend Invitation in Member module developed

2022-10-07 07:35 UTC, yash6102000 commented on app/components/members/MemberListItem.tsx
> +            onClick={() => resendMail()}
please add onkeyup event if not clickable by keyboard

2022-10-10 07:26 UTC, zia-copods commented on app/components/DeletePopUp.tsx
> +                        {t('deletePopUp.alert')} {deleteItemType} '{deleteItem}'
remove changes, if it's not from your side.

2022-10-10 07:26 UTC, zia-copods commented on app/routes/members.tsx
> +  if (action.action === 'resend') {
create a const file. For http methods

2022-10-10 10:27 UTC, zia-copods requested changes

2022-10-10 10:27 UTC, zia-copods commented on app/interface/Interface.tsx
> +export enum memberAction {
Create a const file under `const` folder and add all the actions

2022-10-10 11:25 UTC, zia-copods approved these changes
LGTM!

2022-10-12 07:22 UTC, merged