Feature/storing workspace id in session
copods/kela-quiz pull request #199
Opened 2022-10-06 08:36 UTC by arpita-20

2022-10-06 12:34 UTC, richa-copods requested changes

2022-10-06 12:34 UTC, richa-copods commented on app/models/tests.server.ts
> +export async function getAllTests(obj: any, currentWorkspaceId: string) {
Please give proper type

2022-10-07 05:34 UTC, arpita-20 commented on app/models/tests.server.ts
> +export async function getAllTests(obj: any, currentWorkspaceId: string) {
it is the same bug we are getting earlier that's why not changed the type

2022-10-07 07:23 UTC, anuragP04 commented on app/components/side-nav/SideNav.tsx
> +  const tempWorkspaces = workspaces.map((wk: UserWorkspace) => {
wk?? use some verbose variable names

2022-10-07 07:23 UTC, anuragP04 commented on app/models/tests.server.ts
> +export async function getAllTests(obj: any, currentWorkspaceId: string) {
what is obj here, give some relevant name.....and try to solve any error that is occurring, try avoiding `any` type

2022-10-07 07:23 UTC, anuragP04 commented on app/routes/dashboard.tsx
> +  const workspaces = await getUserWorkspaces(userId)
why workspace is imported here, we don't have dashboard page I think

2022-10-07 07:23 UTC, anuragP04 commented on app/models/result.server.ts
> +export async function getAllCandidateTests(obj: object, workspaceId: string) {
type object?

2022-10-07 07:23 UTC, anuragP04 commented on app/models/sections.server.ts
> +export async function getAllSections(obj: string, currentWorkspaceId: string) {
maintain consistency in naming arguments.....some places you have used `workspaceId` and on some places `currentWorkspaceId`

2022-10-07 09:31 UTC, arpita-20 commented on app/routes/dashboard.tsx
> +  const workspaces = await getUserWorkspaces(userId)
yes we don't have dashboard page.. but when user login they redirected to dashboard page first

2022-10-07 13:45 UTC, richa-copods requested changes

2022-10-07 13:45 UTC, richa-copods commented on app/session.server.ts
> +  return workspaceId?.workspace[0]?.id
Please explain the logic for doing this

2022-10-07 13:45 UTC, richa-copods commented on prisma/migrations/20221007092832_workspace_queries/migration.sql
> +      PERFORM * FROM "UserWorkspace" where "userId"=userList."id" AND "isDefault"=NULL;
Please explain the logic of doing `"isDefault"=NULL` as in Schema we are giving `false` as default value

2022-10-07 13:45 UTC, richa-copods commented on app/models/sections.server.ts
> +  currentWorkspaceId: string
Please maintain consistency in naming of function parameters. Here it's `currentWorkspaceId` and at other places it's `workspaceId`

2022-10-10 05:32 UTC, arpita-20 commented on app/models/tests.server.ts
> +export async function getAllTests(filterData: any, workspaceId: string) {
as told earlier, we were getting stuck here previously, that's why added any here

2022-10-10 05:37 UTC, arpita-20 commented on app/session.server.ts
> +  return workspaceId?.workspace[0]?.id
```
export async function getDefaultWorkspaceIdForUserQuery(userId: string) {
  return prisma.user.findUnique({
    where: { id: userId },
    select: {
      workspace: {
        select: {
          id: true,
        },
      },
    },
  })
}
```

we are adding this function which is returning array as output and we want id of the workspace for every user

2022-10-10 05:39 UTC, arpita-20 commented on app/components/side-nav/SideNav.tsx
>    // {
those commented code will be used in future.. that's why it is there

2022-10-10 07:10 UTC, richa-copods requested changes

2022-10-10 07:10 UTC, richa-copods commented on app/session.server.ts
> +import { User, getDefaultWorkspaceIdForUserQuery } from '~/models/user.server'
Please get rid of this warning

2022-10-10 07:10 UTC, richa-copods commented on prisma/migrations/20221007092832_workspace_queries/migration.sql
> +      PERFORM * FROM "UserWorkspace" where "userId"=userList."id" AND "isDefault"=NULL;
Please check everything is working as expected....

2022-10-10 08:48 UTC, arpita-20 commented on prisma/migrations/20221007092832_workspace_queries/migration.sql
> +      PERFORM * FROM "UserWorkspace" where "userId"=userList."id" AND "isDefault"=NULL;
yes it is working.. i have checked it...

2022-10-11 10:19 UTC, richa-copods approved these changes

2022-10-11 10:37 UTC, merged