111 reset password from inside the application
copods/kela-quiz pull request #231
Opened 2022-10-10 11:29 UTC by yash6102000

2022-10-11 05:42 UTC, yash6102000 commented on app/routes/settings.tsx
> +                title: 'password changed successfully !',
use constant

2022-10-11 09:24 UTC, richa-copods commented on app/models/user.server.ts
> +    oldPass?.password?.hash as any
Please avoid using any

2022-10-11 09:26 UTC, richa-copods commented on app/routes/tests.add-test.tsx
>    const actionData = useActionData() as any
Please avoid using any, and if find at any place please remove it

2022-10-11 09:27 UTC, richa-copods commented on public/locales/en/index.json
> +    "passNotMatch": "password is not matched",
Use capital `P` for password

2022-10-11 09:27 UTC, richa-copods commented on public/locales/hi/index.json
> +    "passNotMatch": "password is not matched",
Please use capital `P` for password

2022-10-12 04:46 UTC, yash6102000 commented on app/components/settings/SettingTab.tsx
> +      name: 'Workspace',
should be in constant

2022-10-13 10:28 UTC, richa-copods commented
Please make suggested changes

2022-10-14 07:38 UTC, anuragP04 commented on app/components/TabsComponent.tsx
> +  currentTab,
you are not using tab component anywhere then why you are taking prop for that

2022-10-14 07:38 UTC, anuragP04 commented on app/components/TabsComponent.tsx
> +            key={tab.id}
do we need key here?

2022-10-14 07:38 UTC, anuragP04 commented on app/components/TabsComponent.tsx
> +              className={`h-1 w-full rounded-1 border-0   ${
don't use location here to do these things, conditional CSS, take reference from sectioncard

2022-10-14 07:38 UTC, anuragP04 commented on app/components/settings/Settings.tsx
> +      <SettingsTabs />
why we have this page here?
if not required, remove it

2022-10-14 07:38 UTC, anuragP04 commented on app/components/settings/SettingTab.tsx
> +    <div>
why do we have multiple divs here?

2022-10-14 07:38 UTC, anuragP04 commented on app/components/settings/GeneralSettings.tsx
> +      <div className="flex flex-col gap-8">
do we need this second div here??

2022-10-14 07:38 UTC, anuragP04 commented on app/components/settings/ResetPassword.tsx
> +  const inputFieldsProps = [
why do we have 2 different config array, make it one

2022-10-14 07:38 UTC, anuragP04 commented on app/components/settings/ResetPassword.tsx
> +                          value="add"
why the value of reset button is `add`

2022-10-14 07:38 UTC, anuragP04 commented on app/routes/settings/general.tsx
> +  if (action === 'add') {
`add` ??

2022-10-14 07:38 UTC, anuragP04 commented on app/routes/settings/general.tsx
> +    const checkOldPassword = await checkOldPasswordFromdb(
first check if new password and reenter new password is same or not then check old password..

2022-10-14 07:38 UTC, anuragP04 commented on app/routes/settings/general.tsx
> +            let valid = 'validationError'
can you explain me what are you doing here?

2022-10-14 07:38 UTC, anuragP04 commented on app/routes/settings/general.tsx
> +    const checkOldPassword = await checkOldPasswordFromdb(
this will not be a separate function, it will give error for thin from reset password fnction

2022-10-14 07:38 UTC, anuragP04 commented on app/models/user.server.ts
> +  const userId = await prisma.user.findUnique({
ye kya ho raha h bhai?

2022-10-18 12:23 UTC, richa-copods requested changes

2022-10-18 12:23 UTC, richa-copods commented on app/components/TabsComponent.tsx
> +const TabComponent = ({ tab }: { tab: any }) => {
Please give proper type, avoid using any

2022-10-18 12:23 UTC, richa-copods commented on app/components/form/InputField.tsx
> +    <div className="flex flex-col gap-1.5">
As this is a global component, please make sure these changes are not affecting other pages

2022-10-18 12:23 UTC, richa-copods commented on app/components/settings/GeneralSettings.tsx
> +  const [openResetPassPopUp, setOpenResetPassPopUp] = useState(false)
It's a modal not pop up, so please rename this

2022-10-18 12:23 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
> +  }, [generalSettings, t])
Please try to get rid of this warning

2022-10-18 12:23 UTC, richa-copods commented on public/locales/en/index.json
> +    "workspace": "Workspace"
Please make it workspaces

2022-10-18 12:29 UTC, richa-copods requested changes

2022-10-18 12:29 UTC, richa-copods commented on app/components/form/PasswordInputField.tsx
> +  const [passwordType, setPasswordType] = useState(type)
Please make it of boolean type.

2022-10-20 05:04 UTC, anuragP04 commented on public/locales/en/index.json
> +    "workspace": "Workspaces"
value and key are not matching

2022-10-20 05:07 UTC, richa-copods requested changes

2022-10-20 05:07 UTC, richa-copods commented on app/constants/common.constants.ts
> +  passNotMatch: 'Password is not matched',
Please make it - "Password does not match". Make this change in locale file also

2022-10-20 05:07 UTC, richa-copods commented on app/constants/common.constants.ts
> +  enterNewPassword: 'Enter New Password',
Why two variables for same constant??

2022-10-20 05:07 UTC, richa-copods commented on app/constants/common.constants.ts
> +  confirmNewPassword: 'Confirm New Password',
Why two variables for same constant??

2022-10-20 05:07 UTC, richa-copods commented on app/constants/common.constants.ts
> +  maximumPasswordLimit: 'Password should have maximum 8 characters only',
Please add msg for minimum characters

2022-10-20 05:07 UTC, richa-copods commented on app/components/form/PasswordInputField.tsx
> +  const [passwordType, setPasswordType] = useState(type)
Please resolve this comment

2022-10-20 05:12 UTC, richa-copods commented on app/components/form/InputField.tsx
> +    <div className="flex flex-col gap-1.5">
Have you verified this??

2022-10-20 06:02 UTC, richa-copods requested changes

2022-10-20 06:02 UTC, richa-copods commented on cypress/e2e/settings-tests/Settings.cy.ts
> +  it('Checking reset password pop up new password input field have focus', () => {
Should have focus on clicking on it or selecting it

2022-10-20 06:22 UTC, yash6102000 commented on app/components/form/InputField.tsx
> +    <div className="flex flex-col gap-1.5">
yes

2022-10-20 07:20 UTC, yash6102000 commented on cypress/e2e/settings-tests/Settings.cy.ts
> +  it('Checking reset password pop up new password input field have focus', () => {
done

2022-10-20 07:21 UTC, yash6102000 commented on app/constants/common.constants.ts
> +  maximumPasswordLimit: 'Password should have maximum 8 characters only',
done

2022-10-20 07:21 UTC, yash6102000 commented on app/constants/common.constants.ts
> +  confirmNewPassword: 'Confirm New Password',
done

2022-10-20 07:21 UTC, yash6102000 commented on app/constants/common.constants.ts
> +  enterNewPassword: 'Enter New Password',
done

2022-10-20 07:21 UTC, yash6102000 commented on app/constants/common.constants.ts
> +  passNotMatch: 'Password is not matched',
done

2022-10-20 07:21 UTC, yash6102000 commented on app/routes/settings/general.tsx
> +    if (typeof newPassword !== 'string' || newPassword.length > 8) {
done

2022-10-20 07:21 UTC, yash6102000 commented on public/locales/en/index.json
> +    "workspace": "Workspaces"
done

2022-10-20 07:25 UTC, yash6102000 commented on app/components/TabsComponent.tsx
> +    if (!isDisabled) return 0
done

2022-10-20 07:27 UTC, yash6102000 commented on app/routes/settings/general.tsx
> +    if (typeof newPassword !== 'string' || newPassword.length >= 8) {
i added this due to newPass length is possibly null

2022-10-20 07:27 UTC, yash6102000 commented on app/models/user.server.ts
> +  console.log('pass', password)
done

2022-10-20 07:27 UTC, yash6102000 commented on app/components/TabsComponent.tsx
> +const TabComponent = ({ tab }: { tab: any }) => {
done

2022-10-20 07:28 UTC, yash6102000 commented on app/components/settings/GeneralSettings.tsx
> +  const [openResetPassPopUp, setOpenResetPassPopUp] = useState(false)
done

2022-10-20 07:28 UTC, yash6102000 commented on app/components/settings/ResetPassword.tsx
> +  }, [generalSettings, t])
done

2022-10-20 07:28 UTC, yash6102000 commented on public/locales/en/index.json
> +    "workspace": "Workspace"
done

2022-10-20 07:29 UTC, yash6102000 commented on app/components/form/PasswordInputField.tsx
> +  const [passwordType, setPasswordType] = useState(type)
done

2022-10-20 07:42 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
> +  }, [generalSettings, t])
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/110384251/196887034-2c1d59da-b3be-4df3-883a-f615c2231a04.png">

2022-10-20 09:53 UTC, richa-copods requested changes

2022-10-20 09:53 UTC, richa-copods commented on app/routes/settings/general.tsx
> +      // checking newly entered password should be less than 8 characters
Update the comment

2022-10-20 09:53 UTC, richa-copods commented on public/locales/en/index.json
> +    "minPasswordLimit": "Password should have minimum 8 characters only",
Remove only

2022-10-20 09:53 UTC, richa-copods commented on app/constants/common.constants.ts
> +  minPasswordLimit: 'Password should have minimum 8 characters only',
Please remove only

2022-10-20 10:01 UTC, yash6102000 commented on public/locales/en/index.json
> +    "minPasswordLimit": "Password should have minimum 8 characters only",
done

2022-10-20 10:01 UTC, yash6102000 commented on app/constants/common.constants.ts
> +  minPasswordLimit: 'Password should have minimum 8 characters only',
done

2022-10-20 10:03 UTC, richa-copods requested changes

2022-10-20 10:13 UTC, yash6102000 commented on app/components/form/PasswordInputField.tsx
> +  const [passwordType, setPasswordType] = useState(false)
done

2022-10-20 10:28 UTC, anuragP04 commented on cypress/e2e/settings-tests/Settings.cy.ts
> +  it('Checking active tab is workspace', () => {
Check if active tab changes to  workspace on clicking on Workspace

2022-10-20 10:28 UTC, anuragP04 commented on cypress/e2e/settings-tests/Settings.cy.ts
> +    cy.get('#Workspaces').should('have.text', tabs.workspace).click()
why are you clicking on workspace again?

2022-10-20 10:28 UTC, anuragP04 commented on cypress/e2e/settings-tests/Settings.cy.ts
> +    cy.get('#Workspaces').should('have.text', tabs.workspace).click()
Why are you clicking on it?

2022-10-20 10:28 UTC, anuragP04 commented on cypress/e2e/settings-tests/Settings.cy.ts
> +  })
Please Correct title of each test cases and remove extra click from each test case, the same issue is in each of them

2022-10-21 04:21 UTC, anuragP04 commented on app/routes/tests.add-test.tsx
>    const actionData = useActionData() as any
@yash6102000

2022-10-21 04:21 UTC, anuragP04 commented on app/components/form/PasswordInputField.tsx
> +  const [password, showPassword] = useState(false)
what is this password, it should be showPassword(true/false), and its state function should be setShowPassword/onShowPasswordChange.

2022-10-21 04:21 UTC, anuragP04 commented on app/components/form/PasswordInputField.tsx
> +  const [passwordType, setPasswordType] = useState(type)
@richa-copods

2022-10-21 04:22 UTC, anuragP04 commented on cypress/e2e/settings-tests/Settings.cy.ts
> +  it('Checking reset password pop up new password input field have focus', () => {
@richa-copods

2022-10-21 04:22 UTC, anuragP04 commented on app/routes/settings/general.tsx
> +      // checking newly entered password should be less than 8 characters
@richa-copods

2022-10-21 04:23 UTC, anuragP04 commented on public/locales/en/index.json
> +    "version": "Version 1.0.0",
remove version form here

2022-10-21 04:23 UTC, anuragP04 commented on app/components/settings/GeneralSettings.tsx
> +              {t('settings.version')}
pick version from package.json

2022-10-21 04:23 UTC, anuragP04 commented on public/locales/en/index.json
> +    "minPasswordLimit": "Password should have minimum 8 characters only",
@richa-copods

2022-10-21 04:24 UTC, anuragP04 commented on app/constants/common.constants.ts
> +  minPasswordLimit: 'Password should have minimum 8 characters only',
@richa-copods

2022-10-21 04:43 UTC, richa-copods requested changes

2022-10-21 04:43 UTC, richa-copods commented on app/constants/common.constants.ts
> +  passNotMatch: 'Password does not match',
Please make it "Password do not match". Update Locales file also

2022-10-21 04:43 UTC, richa-copods commented on app/constants/common.constants.ts
> +  passShouldNotBeSame: 'Your current password and Re-Entered password is same',
Please make it: "Current Password and New Password should not be same". Update in locales file also

2022-10-21 06:13 UTC, richa-copods approved these changes

2022-10-21 06:20 UTC, merged