Feat(): Add Workspace feature
copods/kela-quiz pull request #234
Opened 2022-10-13 06:26 UTC by NitinCopods

Feature : Add & Switch between Workspace
 - User is able to create his own workspace.
 - User is able to switch between his own workspaces and the workspaces he's invited in.

2022-10-14 12:35 UTC, Dhruv-Copods commented on app/components/side-nav/AddWorkspace.tsx
> +                  <label htmlFor="" className="text-gray-800">
Why is htmlFor empty, give it the value of input name

2022-10-14 12:36 UTC, Dhruv-Copods commented on app/components/side-nav/AddWorkspace.tsx
> +                    value={'add'}
No need to use object brackets for normal strings

2022-10-14 12:37 UTC, Dhruv-Copods commented on app/components/side-nav/AddWorkspace.tsx
> +            {/* <Form method="post"> */}
remove this form if not going to use

2022-10-14 12:37 UTC, Dhruv-Copods commented on app/components/side-nav/AddWorkspace.tsx
> +            {/* </Form> */}
remove this form end tag if not going to use

2022-10-14 12:39 UTC, Dhruv-Copods commented on app/routes/results/groupByTests/index.tsx
> +}
what is the use of this function ?

2022-10-14 12:42 UTC, Dhruv-Copods commented on app/routes/sections.tsx
> +          { errors: { title, status: 400, check: new Date() } },
no need to create a variable just to store the string, pass the string directly

2022-10-21 04:13 UTC, anuragP04 commented on app/components/side-nav/AddWorkspace.tsx
> +  }, [fetcher, t, setOpen])
please get rid of this warning

2022-10-21 04:13 UTC, anuragP04 commented on app/components/side-nav/AddWorkspace.tsx
> +                  <input
please use our input component

2022-10-21 04:13 UTC, anuragP04 commented on app/components/side-nav/SideNav.tsx
> +  const [open, setOpen] = useState(false)
can we have more verbose name for these

2022-10-21 04:13 UTC, anuragP04 commented on app/models/workspace.server.ts
> +  const user = await prisma.user.findUnique({
if user is creating workspace, he will be admin for that workspace by default

2022-10-21 04:13 UTC, anuragP04 commented on public/locales/en/index.json
> +    "switched": "Workspace Switched Perfectly"
"Workspace Switched" will be fine here

2022-10-22 12:25 UTC, Dhruv-Copods commented on app/components/form/Dropdown.tsx
> +  console.log({ data })
please remove this console log

2022-10-22 12:30 UTC, Dhruv-Copods commented on app/components/workspace/AddWorkspace.tsx
> +        if (
We can use the && operator and create a single if statement rather than creating 3 different once

2022-10-22 12:31 UTC, Dhruv-Copods commented on app/components/workspace/AddWorkspace.tsx
> +        ) {
We can create a single if statement using && operator rather than creating 3 difference once

2022-10-22 12:39 UTC, Dhruv-Copods commented on app/routes/settings.tsx
> +    let addHandle
it will be better to define what kind of data this variable will hold (e.g. [], {}), so the person reviewing can get a better idea of this variable

2022-10-22 12:43 UTC, Dhruv-Copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
> +          '/members',
If there are constants defined for routes use them ( check routeFiles )

2022-10-22 12:48 UTC, Dhruv-Copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
> +  })
the first test it says we are checking if the dropdown is rendered or not, if thats the case then we need to .click() the dropdown in order to see it. Either the name of first case wrong or the actual written test is wrong. For referance you can see the 2nd test where we are getting the dropdown and actually clicking it in order to get the dropdown

2022-10-25 15:17 UTC, anuragP04 commented on app/components/form/Dropdown.tsx
> +                    value="Add Workspace"
do not make this reusable component dependent of anything .i.e. here workspace

2022-10-27 10:24 UTC, richa-copods requested changes

2022-10-27 10:24 UTC, richa-copods commented on app/components/workspace/AddWorkspace.tsx
> +                    icon={'carbon:close'}
No need to wrap simple strings inside {}

2022-10-27 10:24 UTC, richa-copods commented on app/components/side-nav/SideNav.tsx
> +  const [addWorkspaceModel, setAddWorkspaceModel] = useState(false)
Please name some something 'showAddWorkspaceModal'

2022-10-27 10:24 UTC, richa-copods commented on app/components/form/Dropdown.tsx
> +                        {' '}
Please remove this extra space if needed use html entity for space: &nbsp;

2022-10-27 10:24 UTC, richa-copods commented on app/components/form/Dropdown.tsx
> +                    key="add workspace"
Please use actionName or get it explicitly

2022-10-31 12:03 UTC, richa-copods requested changes

2022-10-31 12:03 UTC, richa-copods commented on app/components/side-nav/SideNav.tsx
> +  }, [workspace])
Please try to remove this warning:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/110384251/199003153-27efcc78-df93-4155-b066-5cdf4ea2a340.png">

2022-10-31 12:03 UTC, richa-copods commented on app/components/side-nav/SideNav.tsx
> +    if (val !== 'Add Workspace' && workspace !== currentWorkspaceId) {
Please use the constant created for "Add Workspace"

2022-10-31 12:32 UTC, yash6102000 commented on app/constants/action.constants.ts
> +  switchWorkspace = 'switch',
it is in use

2022-11-01 06:33 UTC, richa-copods approved these changes

2022-11-01 06:46 UTC, merged