261 test and member related issues
copods/kela-quiz pull request #270
Opened 2022-10-26 10:10 UTC by yash6102000

2022-10-27 07:13 UTC, richa-copods requested changes

2022-10-27 07:13 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +  const newArray = candidateTests.filter(function (
Please use arrow function to maintain the code syntax consistency

2022-10-27 07:13 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +  const newArray = candidateTests.filter(function (
Please give proper name instead of "newArray"

2022-10-27 07:13 UTC, richa-copods commented on app/routes/tests/index.tsx
> +  console.log(testActionData)
Please remove this

2022-10-28 04:24 UTC, anuragP04 commented
The description is missing in this PR, Please add whatever changes you have made. @yash6102000

2022-11-01 06:21 UTC, richa-copods requested changes

2022-11-01 06:21 UTC, richa-copods commented on app/routes/tests/index.tsx
> +    status: number
Can we please name it as "statusCode"

2022-11-01 06:36 UTC, richa-copods approved these changes

2022-11-01 06:45 UTC, merged