[WIP]: Feature/invite candidate
copods/kela-quiz pull request #30
Opened 2022-07-26 08:12 UTC by anuragP04

2022-08-09 08:48 UTC, anuragP04 commented on app/components/QuillEditor.client.tsx
> +      quill.clipboard.dangerouslyPasteHTML(text)
.

2022-08-10 04:39 UTC, richa-copods requested changes

2022-08-10 04:39 UTC, richa-copods commented on app/components/QuillEditor.client.tsx
> +      quill.clipboard.dangerouslyPasteHTML(text)
Please use sanitised text, avoid if not needed

2022-08-16 05:07 UTC, richa-copods approved these changes

2022-08-16 05:07 UTC, merged