309 on add section if user didnt enter description or name and press enter dont show error on toast show error below input
copods/kela-quiz pull request #340
Opened 2022-11-14 14:22 UTC by akshay-copods

2022-11-15 05:15 UTC, richa-copods requested changes

2022-11-15 05:15 UTC, richa-copods commented on app/components/Dialog.tsx
>  import { Dialog, Transition } from '@headlessui/react'
It is a common component, don't modify it for any component specific changes( here: title and description setting)

2022-11-15 05:37 UTC, akshay-copods commented on app/components/Dialog.tsx
>  import { Dialog, Transition } from '@headlessui/react'
I have made requested changes, Please check

2022-11-16 09:40 UTC, richa-copods requested changes

2022-11-16 09:40 UTC, richa-copods commented on app/routes/sections.tsx
> +function validateTitle(title: unknown) {
Use arrow function for code consistency and give proper type. Avoid using any or unknown

2022-11-16 09:40 UTC, richa-copods commented on app/routes/sections.tsx
> +function validateDescription(description: unknown) {
Use arrow function for code consistency and give proper type.

2022-11-16 09:40 UTC, richa-copods commented on app/routes/sections.tsx
> +  fieldErrors?: {
Give proper name. As these are the errors which come while creating section, so name accordingly

2022-11-16 09:40 UTC, richa-copods commented on app/routes/sections.tsx
> +        { errors: { title: 'Form Not submitted Correctly', status: 400 } },
Create constant for this and use common pattern for capitalisation of words

2022-11-16 09:40 UTC, richa-copods commented on app/routes/sections.tsx
> +  const [errorMessage, setErrorMessage] = useState({
Give descriptive name,like addSectionErrorMessage or something similar

2022-11-16 10:46 UTC, richa-copods requested changes

2022-11-16 10:46 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +    title: string
Create common type for this and use that instead of explicitly describing again and again

2022-11-16 10:46 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +          <p className="px-3 text-red-500">{createSectionError.title}</p>
Show this node only when title error is there

2022-11-16 10:46 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +          <p className="px-3 text-red-500">{createSectionError.description}</p>
Show this node only when description error is there

2022-11-16 10:46 UTC, richa-copods commented on public/locales/en/index.json
> +    "FormNotSubmittedCorrectly": "Form Not submitted Correctly",
Add this constants file also

2022-11-17 09:52 UTC, richa-copods requested changes

2022-11-17 09:52 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +            ''
use null instead of empty string or use && operator

2022-11-17 09:52 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +            ''
use null instead of empty string or use && operator

2022-11-17 09:52 UTC, richa-copods commented on app/routes/sections.tsx
> +  createSectionFieldError?: {
Can use `createSectionErrorType` from addSection.tsx

2022-11-18 09:23 UTC, richa-copods requested changes

2022-11-18 09:23 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +export interface createSectionErrorType {
We have an interface file, you can add this there as it is being used in other file also

2022-11-18 09:32 UTC, akshay-copods commented on app/components/sections/AddSection.tsx
> +export interface createSectionErrorType {
moved it interface file.

2022-11-18 10:40 UTC, yash6102000 commented on app/constants/common.constants.ts
> +  FormNotSubmittedCorrectly: 'Form not submitted correctly',
please maintain casing camelCase

2022-11-18 10:40 UTC, yash6102000 commented on app/routes/sections.tsx
> +    return statusCheck.nameIsReq
can we use translation constant here?

2022-11-18 10:40 UTC, yash6102000 commented on app/routes/sections.tsx
> +    return statusCheck.descIsReq
also here?

2022-11-18 10:40 UTC, yash6102000 commented on public/locales/en/index.json
> +    "FormNotSubmittedCorrectly": "Form not submitted correctly",
please use camelCasing

2022-11-18 11:39 UTC, akshay-copods commented on app/routes/sections.tsx
> +    return statusCheck.nameIsReq
In useEffect instead of comparing whole string it becomes convenient to use translation constant there and compare two strings.

2022-11-18 11:58 UTC, akshay-copods commented on app/constants/common.constants.ts
> +  FormNotSubmittedCorrectly: 'Form not submitted correctly',
Done

2022-11-18 11:59 UTC, akshay-copods commented on app/routes/sections.tsx
> +    return statusCheck.nameIsReq
Done

2022-11-18 11:59 UTC, akshay-copods commented on app/routes/sections.tsx
> +    return statusCheck.descIsReq
done

2022-11-18 11:59 UTC, akshay-copods commented on public/locales/en/index.json
> +    "FormNotSubmittedCorrectly": "Form not submitted correctly",
done

2022-11-21 06:00 UTC, richa-copods requested changes

2022-11-21 06:00 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +            <p className="px-3 text-red-500">{createSectionError.title}</p>
Use translation here

2022-11-21 06:00 UTC, richa-copods commented on app/components/sections/AddSection.tsx
> +              {createSectionError.description}
Use translation here

2022-11-21 06:41 UTC, akshay-copods commented on app/components/sections/AddSection.tsx
> +            <p className="px-3 text-red-500">{createSectionError.title}</p>
Done

2022-11-21 06:41 UTC, akshay-copods commented on app/components/sections/AddSection.tsx
> +              {createSectionError.description}
Done

2022-11-21 07:13 UTC, richa-copods approved these changes

2022-11-21 07:29 UTC, merged