Invite candidate Error #299
copods/kela-quiz pull request #345
Opened 2022-11-15 11:00 UTC by akshay-copods

When multiple inputs are there to invite candidates, email will be validated for unfocused fields. 

<img width="414" alt="image" src="https://user-images.githubusercontent.com/117165556/201898254-cb7d321e-e9c9-4956-b1ae-f7038e0543a6.png">

2022-11-17 10:09 UTC, richa-copods requested changes

2022-11-17 10:09 UTC, richa-copods commented on app/components/tests/InviteCandidatePopup.tsx
> +        if (actionData?.candidateInviteStatus.emailCount > 1) {
Write test cases for these new scenarios

2022-11-17 10:09 UTC, richa-copods commented on app/components/tests/InviteCandidatePopup.tsx
> +  const updateEmail = (event: any, index: number) => {
Give proper type to event

2022-11-17 10:09 UTC, richa-copods commented on app/components/tests/InviteCandidatePopup.tsx
> +            emailError[i] = 'Wrong'
Give proper message instead of just "Wrong" also create constant for this

2022-11-18 11:15 UTC, yash6102000 commented on app/components/tests/InviteCandidatePopup.tsx
> +        if (email) {
can we write this in single if condition

2022-11-18 11:15 UTC, yash6102000 commented on cypress/e2e/tests/test-table.cy.ts
> +    const toast = '.Toastify__toast-body'
can we assign it as a global constant instead of assign it for each once

2022-11-18 11:15 UTC, yash6102000 commented on cypress/e2e/tests/test-table.cy.ts
> +      '1 out of 2 Candidates Invited. Others were already invited'
please use constant for toast or status messsages

2022-11-18 11:15 UTC, yash6102000 commented on cypress/e2e/tests/test-table.cy.ts
> +    cy.get('.flex-row > .cursor-pointer').click()
please try to avoid this ....can we get it proper className or id. or by it's label

2022-11-18 11:15 UTC, yash6102000 commented on cypress/e2e/tests/test-table.cy.ts
> +    cy.get(toast).should('have.text', 'All candidates invited.')
please use constants for toast or status checking meassages

2022-11-18 11:32 UTC, richa-copods requested changes

2022-11-18 11:32 UTC, richa-copods commented on cypress/e2e/tests/test-table.cy.ts
> +  it('invite single candidate invite', () => {
Give proper name. For all newly added test cases

2022-11-18 14:51 UTC, akshay-copods commented on cypress/e2e/tests/test-table.cy.ts
> +      '1 out of 2 Candidates Invited. Others were already invited'
Done, thanks for pointing out

2022-11-18 14:51 UTC, akshay-copods commented on cypress/e2e/tests/test-table.cy.ts
> +    cy.get('.flex-row > .cursor-pointer').click()
Done

2022-11-18 14:51 UTC, akshay-copods commented on cypress/e2e/tests/test-table.cy.ts
> +    cy.get(toast).should('have.text', 'All candidates invited.')
done

2022-11-18 14:52 UTC, akshay-copods commented on cypress/e2e/tests/test-table.cy.ts
> +  it('invite single candidate invite', () => {
renamed the test

2022-11-21 07:09 UTC, akshay-copods commented on app/components/tests/InviteCandidatePopup.tsx
> +        if (email) {
Thanks for suggestion, i made the changes

2022-11-21 07:24 UTC, richa-copods approved these changes

2022-11-21 07:30 UTC, merged