307 error showing is abrupt
copods/kela-quiz pull request #347
Opened 2022-11-16 04:26 UTC by akshay-copods

## Update: 
-  **Removed :** Password validation for new password and confirm password after submitting
-  **Added :** Password validation for new password and confirm password , when user starts entering the password is **added**
## Preview
![test3](https://user-images.githubusercontent.com/117165556/202083130-811c5494-34f9-4452-a8d5-5c7c2f0b4aa5.gif)

2022-11-16 09:45 UTC, richa-copods requested changes

2022-11-16 09:45 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
> +    console.log({ password: password.length, confirmPassword })
Remove console

2022-11-16 09:45 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
> +    if (password.length <= 0 || confirmPassword.length <= 0) {
Explain the use case for this logic.

2022-11-17 09:58 UTC, richa-copods requested changes

2022-11-17 09:58 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
> +    if (password.length <= 0 || confirmPassword.length <= 0) {
So shouldn't you be using && operator instead of ||

2022-11-17 09:58 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
> +    console.log({ password: password.length, confirmPassword })
Not removed

2022-11-17 10:13 UTC, akshay-copods commented on app/components/settings/ResetPassword.tsx
> +    console.log({ password: password.length, confirmPassword })
Pushed

2022-11-18 11:36 UTC, richa-copods requested changes

2022-11-18 11:36 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
> +    if (password.length <= 0 || confirmPassword.length <= 0) {
Handle the case when user types in confirm password without filling password field

2022-11-18 11:50 UTC, akshay-copods commented on app/components/settings/ResetPassword.tsx
> +    if (password.length <= 0 || confirmPassword.length <= 0) {
![reset_password_2](https://user-images.githubusercontent.com/117165556/202698616-29a8383a-aaba-407a-a680-8ced45ecb8a6.gif)

2022-11-21 05:55 UTC, richa-copods requested changes

2022-11-21 05:55 UTC, richa-copods commented on app/components/settings/ResetPassword.tsx
>        errorId: 'Confirm-password-error',
Keep kebab-case

2022-11-21 07:08 UTC, akshay-copods commented on app/components/settings/ResetPassword.tsx
>        errorId: 'Confirm-password-error',
Done

2022-11-21 07:15 UTC, richa-copods approved these changes

2022-11-21 07:30 UTC, merged