Feature/remove checkbox
copods/kela-quiz pull request #35
Opened 2022-08-02 05:55 UTC by arpita-20

2022-08-10 07:50 UTC, arshabh-copods requested changes

2022-08-10 07:50 UTC, arshabh-copods commented on app/components/DeletePopUp.tsx
> +                    onClick={() => {
is the onClick method meant to be on Form element or the button element in it ?

2022-08-10 07:50 UTC, arshabh-copods commented on app/components/DeletePopUp.tsx
> +                    onClick={() => {
Create an explicit function to handle the onClick callback - we have multiple lines of code in this inline function

2022-08-10 07:50 UTC, arshabh-copods commented on app/components/MenuItem.tsx
> +  setIsDelete,
Name of the component is `MenuItem` which suggests that this is a generic component. Whereas `setIsDelete` prop suggests that this is specific for delete functionality.
What am i missing ?

2022-08-10 07:50 UTC, arshabh-copods commented on app/components/MenuItem.tsx
> +      <Menu as="div" className="  inline-block text-left">
Why did we need to use inline-block ? is this component supposed to behave like an inline block element always ? If so - please explain why

2022-08-10 07:50 UTC, arshabh-copods commented on app/components/MenuItem.tsx
> +      <Menu as="div" className="  inline-block text-left">
Is this component MenuItem or Menu ? If MenuItem - why do we have Menu component being used here.

2022-08-10 07:50 UTC, arshabh-copods commented on app/components/MenuItem.tsx
> +        <Menu.Items className="absolute right-[7%] w-56 origin-top-left translate-y-[-45px] divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
Why are we setting this menu item to be absolute and right 7% ?? does not seem generic at all

2022-08-10 08:03 UTC, arpita-20 commented on app/components/DeletePopUp.tsx
> +                    onClick={() => {
it should be on the button element... will change that

2022-08-10 08:04 UTC, arpita-20 commented on app/components/MenuItem.tsx
> +  setIsDelete,
the name is wrong... will change that

2022-08-10 09:22 UTC, arshabh-copods requested changes

2022-08-10 09:22 UTC, arshabh-copods commented on app/components/tests/TestDetails.tsx
> +      <div className="max-h-83 overflow-scroll rounded-md shadow-table">
👎🏻 - never do this. you can never for sure that 83% will suffice for all sizes.

2022-08-16 05:33 UTC, richa-copods requested changes

2022-08-16 05:33 UTC, richa-copods commented on app/components/DeletePopUp.tsx
> +  status?: string | null
I think instead of assigning null, we should use undefined because null has type object.

2022-08-16 05:33 UTC, richa-copods commented on app/components/DeletePopUp.tsx
> +    if (status === 'Success') {
Please create enum for status

2022-08-16 05:33 UTC, richa-copods commented on app/components/TestListActionMenu.tsx
> +  onClick: Function
Please give proper name, like onItemClick etc

2022-08-16 05:33 UTC, richa-copods commented on app/components/tests/TestList.tsx
> +                <input type="checkbox"></input>
input is a self closing tag

2022-08-16 05:33 UTC, richa-copods commented on app/components/tests/TestTableItem.tsx
> +// import { Menu } from '@headlessui/react'
Please remove commented code

2022-08-16 05:33 UTC, richa-copods commented on app/components/tests/TestTableItem.tsx
>    createdBy: any
Please use proper type

2022-08-16 05:33 UTC, richa-copods commented on app/components/tests/TestTableItem.tsx
>    id: any
Please use proper type

2022-08-16 05:33 UTC, richa-copods commented on app/routes/tests/index.tsx
> +    status?: string
Status should be an optional field, same for resp

2022-08-16 05:33 UTC, richa-copods commented on cypress/e2e/tests/test-table.cy.ts
> +  const time = new Date().getTime()
Please shift it to the top, hoisting issue might come

2022-08-16 05:33 UTC, richa-copods commented on app/routes/tests/index.tsx
>      toast.success('Something went wrong..!')
This is being used at many places, please create constant for this in constants file

2022-08-16 07:24 UTC, richa-copods requested changes

2022-08-19 13:31 UTC, richa-copods requested changes

2022-08-19 13:31 UTC, richa-copods commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +      .should('have.text', 'Sections')
Please use constants created for these texts, this comment if for all the cypress test cases

2022-08-19 13:31 UTC, richa-copods commented on cypress/e2e/tests/add-test.cy.ts
>    it('Verify if user able create the test and navigate to test list page and see added test there', () => {
Should be---- "Verify if user is able to create a test and navigates to Tests Page where can see added test"

2022-08-19 13:31 UTC, richa-copods commented on cypress/e2e/tests/test-table.cy.ts
> +let totalCount: any
Please give proper type

2022-08-19 13:31 UTC, richa-copods commented on cypress/e2e/tests/test-table.cy.ts
> +  it('By Clicking count in sections it should open menu with all sections', () => {
should be "On click of count in sections, menu with all sections should open"

2022-08-19 13:31 UTC, richa-copods commented on cypress/e2e/tests/test-table.cy.ts
> +  let deletedItem: any
Please give proper type

2022-08-19 13:31 UTC, richa-copods commented on cypress/e2e/tests/test-table.cy.ts
> +  it('On Clicking delete it should delete the test', () => {
Should be: "On click of delete, test should be deleted"

2022-08-19 13:31 UTC, richa-copods commented on cypress/e2e/tests/testPreview.cy.ts
> +  it('Verify if user able create the test and navigate to test list page', () => {
Should be: "Verify if user is able to create test and gets navigated to Tests' List Page"

2022-08-19 13:31 UTC, richa-copods commented on prisma/migrations/20220803122419_new/migration.sql
> +ALTER TABLE "Test" ADD COLUMN     "deleted" BOOLEAN NOT NULL DEFAULT false;
Please remove extra space

2022-08-19 13:31 UTC, richa-copods commented on prisma/migrations/20220804091159_new/migration.sql
> +ALTER TABLE "Test" ADD COLUMN     "deleteAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
Please remove extra space

2022-08-19 13:31 UTC, richa-copods commented on prisma/migrations/20220804090334_new/migration.sql
> +ALTER TABLE "Test" ADD COLUMN     "deleted" BOOLEAN NOT NULL DEFAULT false;
Please remove extra space

2022-08-19 13:31 UTC, richa-copods commented on prisma/migrations/20220808093419_new/migration.sql
> +ADD COLUMN     "deletedAt" TEXT DEFAULT E'na';
Please remove extra space

2022-08-19 13:31 UTC, richa-copods commented on tailwind.config.js
> +      boxShadow: {
Please remove if not being used

2022-08-22 05:18 UTC, arpita-20 commented on prisma/migrations/20220803122419_new/migration.sql
> +ALTER TABLE "Test" ADD COLUMN     "deleted" BOOLEAN NOT NULL DEFAULT false;
THIS HAS BEEN NOT BEEN CREATED MANUALLY RICHA

2022-08-22 05:18 UTC, arpita-20 commented on tailwind.config.js
> +      boxShadow: {
IT IS BEING USED

2022-08-22 07:40 UTC, richa-copods requested changes

2022-08-22 07:40 UTC, richa-copods commented on app/components/tests/ChipGroup.tsx
> +                  <div className="section-menu flex flex-col px-2 py-2">
Please add key here

2022-08-22 07:40 UTC, richa-copods commented on app/components/tests/TestList.tsx
>    const [sortDirection, onSortDirectionChange] = useState('asc')
Use enum here. @yash6102000 has created, you can sync with his code

2022-08-22 07:40 UTC, richa-copods commented on app/components/tests/TestList.tsx
>    const [sortBy, onSortChange] = useState('name')
Please use enum here

2022-08-22 07:40 UTC, richa-copods commented on app/constants/common.constants.ts
> +export const cypress = {
No need to create new or duplicate constants, please use the existing one

2022-08-22 07:40 UTC, richa-copods commented on app/models/tests.server.ts
> +  var filter = obj.orderBy ? obj : { orderBy: { name: 'asc' } }
Please use let, also use enum for `asc`

2022-08-22 12:04 UTC, richa-copods requested changes

2022-08-23 08:34 UTC, richa-copods approved these changes

2022-08-23 08:36 UTC, arshabh-copods approved these changes

2022-08-23 08:37 UTC, merged