324 add test cases for ctas and title texts
copods/kela-quiz pull request #365
Opened 2022-11-23 06:25 UTC by akshay-copods

Ran updated test with CLI, here is result: 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/117165556/203483981-97dbc6ce-c235-476b-9837-ac92d5852d7e.png">

2022-11-23 07:22 UTC, yash6102000 commented on cypress/e2e/tests/add-test.cy.ts
> +    cy.get('#next-button').click()
please use assertion

2022-11-23 07:22 UTC, yash6102000 commented on cypress/e2e/tests/add-test.cy.ts
> +    cy.get('#next-button').click()
please use assertion

2022-11-23 07:22 UTC, yash6102000 commented on cypress/e2e/tests/add-test.cy.ts
> +    cy.get('#next-button').click()
please use assertion

2022-11-23 07:22 UTC, yash6102000 commented on cypress/e2e/tests/add-test.cy.ts
> +    cy.get('#next-button').click()
please use assertion

2022-11-23 07:22 UTC, yash6102000 commented on cypress/e2e/tests/add-test.cy.ts
> +    cy.get('#next-button').click()
please use assertion

2022-11-24 09:17 UTC, richa-copods requested changes

2022-11-24 09:17 UTC, richa-copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
> +  it('Checks text SideNavTitle- Results', () => {
Give better name instead of SideNavTitle, for all below test cases

2022-11-24 09:17 UTC, richa-copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
Add text case for User Name, email and name initials at the bottom of Sidenav

2022-11-24 09:17 UTC, richa-copods commented on cypress/e2e/sign-up/SignUp.cy.ts
> +  it('Checks for Sing Up CTA button text', () => {
Correct the spelling of sign up

2022-11-24 09:17 UTC, richa-copods commented on cypress/e2e/tests/add-test.cy.ts
> +  it('Checks next button padding', () => {
Add test case to check the text color

2022-11-24 09:31 UTC, akshay-copods commented on cypress/e2e/sign-up/SignUp.cy.ts
> +  it('Checks for Sing Up CTA button text', () => {
Done

2022-11-24 09:36 UTC, akshay-copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
> +  it('Checks text SideNavTitle- Results', () => {
Done

2022-11-24 10:01 UTC, akshay-copods commented on cypress/e2e/tests/add-test.cy.ts
> +  it('Checks next button padding', () => {
Done

2022-11-24 11:04 UTC, akshay-copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
Done

2022-11-24 11:35 UTC, richa-copods requested changes

2022-11-24 11:35 UTC, richa-copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
> +  it('Checks text SideNav group title- Results', () => {
Checks text of..

2022-11-24 11:35 UTC, richa-copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
> +  it('Checks text SideNav group title- General', () => {
Checks text of....

2022-11-24 11:35 UTC, richa-copods commented on cypress/e2e/side-nav-tests/SideNavTests.cy.ts
> +  it('Checks for sideNav user email font size', () => {
Check for font-weight

2022-11-24 11:35 UTC, richa-copods commented on cypress/e2e/tests/add-test.cy.ts
> +  it('Checks add assessment page title text', () => {
Add test case for color

2022-11-24 11:35 UTC, richa-copods commented on cypress/e2e/tests/add-test.cy.ts
> +  it('Checks next button background color', () => {
Add test case to check cursor pointer

2022-11-24 11:35 UTC, richa-copods commented on cypress/e2e/tests/add-test.cy.ts
> +  it('Checks back button padding', () => {
Add test case for cursor pointer

2022-11-24 11:35 UTC, richa-copods commented on cypress/e2e/tests/add-test.cy.ts
> +  it('Checks submit button padding', () => {
Add test case for cursor pointer

2022-11-24 13:19 UTC, richa-copods approved these changes

2022-11-24 13:20 UTC, merged