195: MCQ vs SCQ fix
copods/kela-quiz pull request #370
Opened 2022-11-24 12:50 UTC by akshay-copods

2022-11-24 13:20 UTC, richa-copods requested changes

2022-11-24 13:20 UTC, richa-copods commented on app/components/form/Dropdown.tsx
> +    (item) => item.value !== 'SINGLE_CHOICE'
Add ENUM here

2022-11-24 13:20 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +    question.questionType?.displayName === 'Multiple Choice'
Use ENUM for question type

2022-11-24 13:20 UTC, richa-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +    for (let qt of questionTypes) {
Give proper name

2022-11-24 13:20 UTC, richa-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +          ? questionTypes.find((item: any) => item.value === 'SINGLE_CHOICE')
Give proper type. and use ENUM fir item.value

2022-11-24 13:32 UTC, akshay-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +          ? questionTypes.find((item: any) => item.value === 'SINGLE_CHOICE')
Done

2022-11-24 13:32 UTC, akshay-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +    for (let qt of questionTypes) {
Done

2022-11-24 13:33 UTC, akshay-copods commented on app/components/sections/QuestionCard.tsx
> +    question.questionType?.displayName === 'Multiple Choice'
Done

2022-11-24 13:33 UTC, akshay-copods commented on app/components/form/Dropdown.tsx
> +    (item) => item.value !== 'SINGLE_CHOICE'
Done

2022-11-25 08:58 UTC, richa-copods requested changes

2022-11-25 08:58 UTC, richa-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +      if (questionType.value == 'MULTIPLE_CHOICE') {
Use ENUM for "MULTIPLE_CHOICE"

2022-11-25 08:58 UTC, richa-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
>        toast.error('Enter the Question', { toastId: 'questionRequired' })
Create constant for this

2022-11-25 08:58 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +      ? { name: 'MSQ', full: 'Multiple Select Question' }
Use constants here

2022-11-25 08:58 UTC, richa-copods commented on app/components/form/Dropdown.tsx
> +                {createQuestionDropdownOptions.map((el) => (
give proper name instead of el

2022-11-25 08:58 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +              {displayName?.name}
Use translation

2022-11-25 10:28 UTC, akshay-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +      if (questionType.value == 'MULTIPLE_CHOICE') {
Done

2022-11-25 10:31 UTC, akshay-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
>        toast.error('Enter the Question', { toastId: 'questionRequired' })
Done

2022-11-25 10:36 UTC, akshay-copods commented on app/components/sections/QuestionCard.tsx
> +      ? { name: 'MSQ', full: 'Multiple Select Question' }
Done

2022-11-25 11:05 UTC, akshay-copods commented on app/components/form/Dropdown.tsx
> +                {createQuestionDropdownOptions.map((el) => (
done

2022-11-25 11:24 UTC, richa-copods requested changes

2022-11-25 11:24 UTC, richa-copods commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +      if (questionType.value == QuestionTypes.multipleChoice) {
Use strict check ===

2022-11-25 11:25 UTC, richa-copods approved these changes

2022-11-25 11:26 UTC, merged