common_component_folder_Created
copods/kela-quiz pull request #447
Opened 2022-11-30 05:12 UTC by yash6102000

2022-11-30 12:23 UTC, richa-copods requested changes

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/Pagination.tsx
> +  // const totalCount = Math.ceil(totalLength / pageSize)
Remove unwanted comments

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/Pagination.tsx
> +  const paginationRange: any[] | undefined = usePagination({
Give proper type. Avoid using any

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/Pagination.tsx
> +  const itemsList = [
It should be passed from parent and should be dynamic

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/Pagination.tsx
> +      <div className="">
Remove classname

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/Pagination.tsx
> +    <>
Fragment isn't needed here

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/usePagination.js
> +
Change file type to tsx and define types

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/usePagination.js
> +    const totalPageNumbers = siblingCount + 5
Why hardcoding totalPageNumbers?

2022-11-30 12:23 UTC, richa-copods commented on app/components/common_components/pagination/usePagination.js
> +import { useMemo } from 'react'
What is the purpose of this file?

2022-11-30 12:23 UTC, richa-copods commented on app/components/SideNavFooter.tsx
> +import Button from './common_components/Button'
Component folders' names should be kebab-case. Follow ReadME.md file

2022-12-02 11:48 UTC, akshay-copods requested changes

2022-12-02 11:48 UTC, akshay-copods commented on app/components/common-components/pagination/Pagination.tsx
> +  const paginationRange: Array<any> | undefined = usePagination({
Please give proper type.

2022-12-05 11:06 UTC, akshay-copods approved these changes

2022-12-07 04:34 UTC, anuragP04 approved these changes

2022-12-07 04:36 UTC, merged