Feature/results group by tests
copods/kela-quiz pull request #47
Opened 2022-08-12 16:46 UTC by yash6102000

2022-08-16 12:48 UTC, richa-copods requested changes

2022-08-16 12:48 UTC, richa-copods commented on app/interface/Interface.tsx
> +  testId?: String
`testId` should not be constant, if still required, please specify the reason

Also use primitive data type, i.e `string`

2022-08-16 12:48 UTC, richa-copods commented on app/models/result.server.ts
> +export async function getAllCandidateTests(obj: any) {
Please give proper type instead of any

2022-08-16 12:48 UTC, richa-copods commented on app/models/result.server.ts
> +  var filter = obj ? obj : {}
Please use const here

2022-08-16 12:48 UTC, richa-copods commented on app/models/result.server.ts
> +  var res = await prisma.test.findMany({
Please use const here, as not being reassigned

2022-08-16 12:48 UTC, richa-copods commented on app/models/result.server.ts
> +      console.log('test:', test)
Please remove console

2022-08-16 12:48 UTC, richa-copods commented on app/routes/results/index.tsx
> +// export type ActionData = {
Please remove commented code

2022-08-16 12:48 UTC, richa-copods commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +  let time = new Date().getTime()
Please use const

2022-08-16 12:48 UTC, richa-copods commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +  let value: any
Please give proper type

2022-08-16 12:48 UTC, richa-copods commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +  let strings: any
Please give proper name and type

2022-08-16 12:48 UTC, richa-copods commented on tailwind.config.js
> +        83: '83.3%',
Please remove this if not being used

2022-08-16 12:48 UTC, richa-copods commented on app/components/members/MembersList.tsx
> +        <div className="col-span-full grid grid-cols-10 bg-tableHeader py-4 px-12">
Please only required number of columns, avoid using span

2022-08-16 12:48 UTC, richa-copods commented on app/components/results/GroupByTestItems.tsx
> +        className="col-span-full grid grid-cols-10 gap-3 border-t border-solid border-[#E5E7EB] px-12 py-4"
Please create only the required number of columns, avoid using span

2022-08-16 12:48 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +          <div className="col-span-full grid grid-cols-10 rounded-lg border-[1px] border-solid border-[#E5E7EB] bg-white">
Please create only the required number of columns, avoid using span

2022-08-16 12:48 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +                  i: number
Please give proper name, don't use `i`, `x` as variable names

2022-08-16 12:48 UTC, richa-copods commented on app/interface/Interface.tsx
> +  link: String
Please use primitive data type, i.e., `string`

2022-08-16 12:48 UTC, richa-copods commented on app/interface/Interface.tsx
> +  candidateId?: String
Please use primitive data type, i.e., `string`

2022-08-16 12:48 UTC, richa-copods commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +          cy.wait(1000)
Avoid using wait

2022-08-16 12:48 UTC, richa-copods commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +          cy.wait(1000)
Please avoid using wait

2022-08-16 12:48 UTC, richa-copods commented on tailwind.config.js
> +      boxShadow: {
Please remove this if not being used

2022-08-16 12:48 UTC, richa-copods commented on app/models/result.server.ts
> +    res.map((test: any) => {
Please give proper type, avoid using any

2022-08-16 12:48 UTC, richa-copods commented on app/models/result.server.ts
> +        if (candidateTest?.endAt !== null) {
Are you sure it is not going to be undefined? if yes ignore else implement proper check

2022-08-16 12:48 UTC, richa-copods commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +          cy.wait(1000)
Please avoid using wait

2022-08-22 07:29 UTC, arpita-20 commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +      .should('have.value', 'careers@copods.co')
make common constants name cypress and add email:'careers@copods.co'

2022-08-22 07:29 UTC, arpita-20 commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +      .should('have.value', 'kQuiz@copods')
add password:'kQuiz@copods'

2022-08-22 07:29 UTC, arpita-20 commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +    cy.get('a').find('#Results').should('have.text', 'Results').click()
results: 'Results'

2022-08-22 07:29 UTC, arpita-20 commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +    cy.get('a').find('#Sections').should('have.text', 'Sections').click()
add common constants as discussed evrywhere

2022-08-22 07:47 UTC, richa-copods requested changes

2022-08-22 07:47 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +      <h1 className="text-3xl font-bold text-gray-900 ">Group by tests</h1>
Please remove extra space

2022-08-22 07:47 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +              <span className="col-span-2 text-sm  font-semibold  text-gray-500">
Please remove extra space... same for next three spans

2022-08-22 07:47 UTC, richa-copods commented on app/constants/common.constants.ts
>  export const commonMembers = {
Please give proper name... maybe something, `membersConstant`

2022-08-22 07:47 UTC, richa-copods commented on app/routes/results/index.tsx
> +export default function ResultsIndex() {
Please use arrow function

2022-08-22 07:47 UTC, richa-copods commented on prisma/migrations/20220817061545_/migration.sql
> +ALTER TABLE "Test" ADD COLUMN     "count" INTEGER NOT NULL;
Please remove extra space

2022-08-22 07:47 UTC, richa-copods commented on prisma/migrations/20220817065430_count_in_test/migration.sql
> +ALTER TABLE "Test" ADD COLUMN     "count" INTEGER NOT NULL;
Please remove extra space

2022-08-22 07:47 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +    commonConstants.ascending
Please create enum for this instead of constant

2022-08-22 07:47 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +      value: commonConstants.nameSmallEach,
No need to create constant for this

2022-08-22 07:47 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +      value: commonConstants.createdAt,
No need to create constant for this

2022-08-22 07:47 UTC, richa-copods commented on app/models/result.server.ts
> +export async function getAllCandidateTests(obj: string) {
Please give proper name to the parameter, `obj: string` how can object be of type string?

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
> +  candidateTests: Test & { count?: number; candidateTest?: CandidateTest }
why fields are optional?

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
> +      <div className="col-span-full grid grid-cols-10 gap-3 border-t border-solid border-[#E5E7EB] px-12 py-4">
don't use hardcoded value, this color is available in tailwind.config

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
> +          <Link tabIndex={0} to={'/'}>
why to has value /, it should redirect to its detail page

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
> +            <span className="  text-base font-semibold   text-primary">
why there are too many extra space

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
> +            <span className="  text-base font-semibold   text-primary">
we can style this inside link tag, do we need span here?

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
> +          <span className=" text-base leading-6 text-gray-700">
span is not needed here

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTests.tsx
> +          <div className="col-span-full grid grid-cols-10 rounded-lg border-[1px] border-solid border-[#E5E7EB] bg-white">
don't use hardcoded value, this color is available in tailwind.config

2022-08-22 14:43 UTC, anuragP04 commented on app/components/results/GroupByTests.tsx
> +        <div className="grid grid-cols-12 rounded-lg  bg-[#F9FAFB] shadow-table">
don't use hardcoded value, this color is available in tailwind.config

2022-08-22 14:51 UTC, anuragP04 approved these changes

2022-08-22 14:52 UTC, merged