bug-fix-addTest
copods/kela-quiz pull request #48
Opened 2022-08-18 09:49 UTC by DhruvCopods

Fixed the following issue:
- In Add Test, Step 2 and Step 3 were accessible while the name and description fields were empty, those clickable steps were creating UI flickering

2022-08-18 10:01 UTC, richa-copods requested changes

2022-08-18 10:01 UTC, richa-copods commented on app/components/tests/AddTest.tsx
> +        name={name}
Instead of sending `name` and `description` we can directly pass a boolean prop called isActive

2022-08-18 10:21 UTC, DhruvCopods commented on app/components/tests/StepsTab.tsx
> +            name !== '' && description !== '' && setCurrentTab(tab.id)
Changed the class to pointer-events-none, thanks for pointing it out

2022-08-18 10:23 UTC, DhruvCopods commented on app/components/tests/AddTest.tsx
> +        name={name}
Thanks for pointing it out, created isEmpty boolean prop

2022-08-18 10:43 UTC, DhruvCopods commented on app/components/tests/StepsTab.tsx
> +          className={`flex-1 ${name === '' || description === '' && currentTab !== tab.id ? 'cursor-not-allowed' : 'cursor-pointer'}`}
Created a isEmpty boolean prop, also while rechecking the code the currentTab condition was not necessary so I have removed that.

2022-08-18 11:46 UTC, anuragP04 commented on app/components/tests/StepsTab.tsx
> +            setCurrentTab(tab.id)
You are only disabling click using css, but ideally setCurrentTab function should also be blocked/disabled to avoid glitch in case I change CSS property.

2022-08-18 11:54 UTC, DhruvCopods commented on app/components/tests/StepsTab.tsx
> +            setCurrentTab(tab.id)
Added conditional calling to setCurrentTab

2022-08-18 12:06 UTC, arshabh-copods requested changes

2022-08-18 12:06 UTC, arshabh-copods commented on app/components/tests/StepsTab.tsx
> +            !isDisabled && setCurrentTab(tab.id)
with pointer-events-none - this is not needed

2022-08-18 12:57 UTC, DhruvCopods commented on app/components/tests/StepsTab.tsx
> +            !isDisabled && setCurrentTab(tab.id)
removed the condition

2022-08-19 07:18 UTC, arshabh-copods approved these changes

2022-08-22 06:45 UTC, anuragP04 approved these changes

2022-08-22 06:46 UTC, richa-copods approved these changes

2022-08-22 06:47 UTC, merged