402 record result of candidate on ongoing exam dont wait for exam to end and then calculate result
copods/kela-quiz pull request #495
Opened 2022-12-14 08:31 UTC by yash6102000

2022-12-26 04:46 UTC, anuragP04 commented
<img width="1384" alt="Screenshot 2022-12-26 at 10 16 21 AM" src="https://user-images.githubusercontent.com/106807559/209502303-409350ea-3f93-4d43-8a3b-fc58e488cf4a.png">
When the test is ongoing, we have his name so display it and make it clickable

2022-12-26 05:37 UTC, anuragP04 commented
Please make all the changes that we have discussed.

2022-12-28 13:38 UTC, anuragP04 commented on app/components/barGraph/barGraph.tsx
> +  candidateTestWiseResult: Array<any>
avoid any..

2023-01-05 02:55 UTC, anuragP04 commented on app/routes/$workspaceId/results/groupByTests/$testId.$candidateId.tsx
> +  const candidateTestWiseResult =
you are getting section wise result and naming it test wise result...

2023-01-05 02:55 UTC, anuragP04 commented on app/components/results/ResultDetails.tsx
> +  const { params, candidateTestWiseResult, currentWorkspaceId } =
candidate testWiseResult can be candidateTestResult

2023-01-05 02:55 UTC, anuragP04 commented on app/components/results/ResultDetails.tsx
> +            {sortSections.reverse().map((section: SectionInCandidateTest) => {
instad of using reverse, we can have sort in reverse order

2023-01-05 02:55 UTC, anuragP04 commented on app/components/barGraph/barGraph.tsx
> +  candidateTestWiseResult,
it can be candidateTestResult

2023-01-05 02:55 UTC, anuragP04 commented on app/components/barGraph/barGraph.tsx
> +  })
can you add comment what these lines are doing

2023-01-05 02:55 UTC, anuragP04 commented on app/components/barGraph/barGraph.tsx
> +        (getRequiredSection[0]?.SectionWiseResult[0]?.totalQuestion as number) -
why we are using hardcoded index here?

2023-01-05 02:55 UTC, anuragP04 commented on app/models/assessment.server.ts
> +async function calculateResultByIdSection(sectionid?: string) {
does this name make any sense??

2023-01-05 05:37 UTC, yash6102000 commented on app/components/barGraph/barGraph.tsx
> +  })
discussed

2023-01-05 07:37 UTC, richa-copods requested changes

2023-01-05 07:37 UTC, richa-copods commented on app/components/barGraph/barGraph.tsx
> +      let data = results.section.section.sectionInTest.map(
Use `const` and rename

2023-01-05 07:37 UTC, richa-copods commented on app/components/results/AttendedCandidateListItem.tsx
>            {result >= 0 ? (
Change the condition to `result<0`

2023-01-05 07:37 UTC, richa-copods commented on app/models/assessment.server.ts
> +        question?.answers.length == 0 &&
Use strict check `===`. For entire file

2023-01-06 08:29 UTC, anuragP04 approved these changes

2023-01-06 09:49 UTC, merged