soft-delete-question
copods/kela-quiz pull request #496
Opened 2022-12-14 10:38 UTC by yash6102000

2022-12-14 15:28 UTC, akshay-copods requested changes

2022-12-14 19:25 UTC, richa-copods requested changes

2022-12-14 19:25 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +            delete
We have icon in design, then why text?

2022-12-14 19:25 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +  const [open, setOpen] = useState(false)
Give proper name.

2022-12-14 19:25 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +            aria-label=""
Provide aria-label

2022-12-14 19:25 UTC, richa-copods commented
Add Test Cases

2022-12-22 06:26 UTC, akshay-copods commented on app/components/sections/QuestionCard.tsx
> + <Icon
Format this properly

2022-12-22 06:41 UTC, akshay-copods approved these changes

2022-12-26 09:18 UTC, richa-copods requested changes

2022-12-26 09:18 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    let deleteHandle = null
no need to create this extra variable

2022-12-26 09:18 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    if (section) {
This if can be removed-- `if (section?.resp?.status === 200)`

2022-12-26 09:18 UTC, richa-copods commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +  it('checks, delete question button should be exist', () => {
"Checks if Delete Question button exists"

2022-12-26 09:18 UTC, richa-copods commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +    cy.get('.sectionCard', { timeout: 40000 }).each(($el) => {
Why giving so much timeout?

2022-12-26 09:18 UTC, richa-copods commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +    cy.get('#sections', { timeout: 8000 }).should('have.text', 'Tests').click()
Why giving so much timeout?

2022-12-26 09:18 UTC, richa-copods commented on cypress/e2e/smoke.cy.ts
> +    cy.visit('/sign-in')
We have function for login, use that. Avoid writing manually.

2022-12-26 09:18 UTC, richa-copods commented on cypress/e2e/smoke.cy.ts
> +    cy.get('#sections', { timeout: 8000 }).should('have.text', 'Tests').click()
Avoid using such big timeout anywhere..!

2022-12-28 12:32 UTC, richa-copods requested changes

2022-12-28 12:32 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    if (section && section.resp?.status === 200) {
you could have used optional chaining--> `if(section?.resp?.status === 200)`

2022-12-28 12:32 UTC, richa-copods commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +  it('"Checks if Delete Question button exists"', () => {
Remove extra quotes around string

2022-12-28 12:32 UTC, richa-copods commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +    cy.get('.sectionCard', { timeout: 8000 }).each(($el) => {
Avoid giving this much timeout. (For entire file)

2023-01-03 03:01 UTC, richa-copods requested changes

2023-01-03 03:01 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    if (section && section.resp?.status === 200) {
Resolve this

2023-01-03 03:01 UTC, richa-copods commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +  it('"Checks if Delete Question button exists"', () => {
resolve this

2023-01-04 08:24 UTC, richa-copods requested changes

2023-01-04 08:24 UTC, richa-copods commented on app/components/common-components/DeletePopUp.tsx
> +  deleteItem?: string
Why is this marked as optional?

2023-01-04 08:24 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +                  e.stopPropagation()
Format the file

2023-01-04 08:24 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +            {isExpanded === index ? (
`isExpanded` is not a appropriate name for a variable of type number

2023-01-04 08:24 UTC, richa-copods commented on app/components/tests/CreateSelectSections.tsx
> +            {sections.map((section: TestSection & { count?: number }, i) => {
Why count is optional?

2023-01-04 08:24 UTC, richa-copods commented on app/models/sections.server.ts
> +  console.log(id, 'id')
Remove this console

2023-01-04 08:24 UTC, richa-copods commented on app/components/tests/SelectSectionCard.tsx
> +        <span className="count">{sectionCount}</span>
As sectionCount is optional, shouldn't this have any default value?

2023-01-04 08:24 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +return deleteQuestion
Format the file

2023-01-04 08:24 UTC, richa-copods commented on cypress/e2e/smoke.cy.ts
>      cy.get('#tests', { timeout: 60000 })
Avoid such large timeout(For all the tests in this PR)

2023-01-04 08:31 UTC, richa-copods commented on cypress/e2e/smoke.cy.ts
> +    cy.get('#sections', { timeout: 8000 }).should('have.text', 'Tests').click()
Resolve this

2023-01-04 11:03 UTC, yash6102000 commented on app/components/sections/QuestionCard.tsx
> +            {isExpanded === index ? (
please suggest name for this

2023-01-05 04:11 UTC, yash6102000 commented on cypress/e2e/smoke.cy.ts
> +    cy.get('#sections', { timeout: 8000 }).should('have.text', 'Tests').click()
done

2023-01-05 04:12 UTC, yash6102000 commented on cypress/e2e/add-questions/AddQuestion.cy.ts
> +  it('"Checks if Delete Question button exists"', () => {
done

2023-01-05 04:12 UTC, yash6102000 commented on app/interface/Interface.tsx
> +  deleted: boolean
as per documentation ......Deleted is a fine name

2023-01-05 04:13 UTC, yash6102000 commented on app/components/common-components/DeletePopUp.tsx
> +  deleteItem?: string
because in question delete we are not showing question in popup...that's why optional

2023-01-05 04:13 UTC, yash6102000 commented on app/components/sections/QuestionCard.tsx
> +                  e.stopPropagation()
done

2023-01-05 04:13 UTC, yash6102000 commented on app/components/tests/CreateSelectSections.tsx
> +            {sections.map((section: TestSection & { count?: number }, i) => {
because count is not in testSection it's a optional

2023-01-05 04:13 UTC, yash6102000 commented on app/models/sections.server.ts
> +  console.log(id, 'id')
done

2023-01-05 04:14 UTC, yash6102000 commented on app/components/tests/SelectSectionCard.tsx
> +        <span className="count">{sectionCount}</span>
default value is 0 please check backend where it's calculated

2023-01-05 04:14 UTC, yash6102000 commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +return deleteQuestion
done

2023-01-05 04:14 UTC, yash6102000 commented on cypress/e2e/smoke.cy.ts
>      cy.get('#tests', { timeout: 60000 })
done

2023-01-05 07:41 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +            {isExpanded === index ? (
expandedIndex

2023-01-05 10:29 UTC, yash6102000 commented on app/components/tests/SelectSectionCard.tsx
> +        <span className="count">{sectionCount}</span>
i made this optionol at from where it passed...

2023-01-06 13:32 UTC, richa-copods commented on cypress/e2e/smoke.cy.ts
> +    cy.get('#sections', { timeout: 8000 }).should('have.text', 'Tests').click()
Not done

2023-01-12 08:51 UTC, richa-copods approved these changes

2023-01-12 08:52 UTC, merged