469 zia
copods/kela-quiz pull request #498
Opened 2022-12-14 16:35 UTC by zia-copods

<img width="1680" alt="Screenshot 2022-12-14 at 10 04 21 PM" src="https://user-images.githubusercontent.com/108815583/207653914-f14d0035-e02a-4ec8-b162-bee2d8fafd4e.png">

2022-12-14 17:08 UTC, arshabh-copods requested changes

2022-12-14 17:08 UTC, arshabh-copods commented on app/components/members/MemberListItem.tsx
> +            ) : null}
it would be better if you use the following convention for conditional display
```javascript
{ owner && (...) }
```
instead of ternary operator

2022-12-14 17:08 UTC, arshabh-copods commented on app/components/members/MemberListItem.tsx
> +            {user.firstName} {user.lastName}{' '}
put the first name and last name in one div and the owner tag in another div. make the parent flex

2022-12-14 19:08 UTC, richa-copods requested changes

2022-12-14 19:08 UTC, richa-copods commented on app/components/members/MemberListItem.tsx
> +            ) : null}
Also add test case for this

2022-12-15 15:42 UTC, zia-copods commented on app/components/members/MembersList.tsx
> +            <div key={user.id} className="memberRow col-span-10 grid">
`memberRow` is not added by removing it as upon search I didn't any CSS class with name

2022-12-15 15:56 UTC, zia-copods commented on app/components/members/MemberListItem.tsx
> +            ) : null}
`{ owner && (...) }` is a potential UI bug. Ternary operator is a best way to add conditional rendering.

Test case added.

2022-12-15 15:56 UTC, zia-copods commented on app/components/members/MemberListItem.tsx
> +            {user.firstName} {user.lastName}{' '}
resolved

2022-12-19 04:43 UTC, richa-copods commented
Get the design of Owner tag verified by @yashwants64 , this isn't looking nice

2022-12-19 08:43 UTC, arshabh-copods commented on app/components/members/MemberListItem.tsx
> +            ) : null}
ok - i read some articles and looks like ternary operator is good choice over &&.

2022-12-19 09:55 UTC, richa-copods requested changes

2022-12-19 09:55 UTC, richa-copods commented on app/components/members/MemberListItem.tsx
> +          <span className="memberName flex gap-1 text-base text-gray-700">
Use snake_case to name CSS classes. If this is only being used for test cases then get rid of this and use `data-cy` instead.

2022-12-19 09:55 UTC, richa-copods commented on app/components/members/MemberListItem.tsx
> +                  owner
Create constant for this

2022-12-19 11:21 UTC, richa-copods commented on app/components/members/MemberListItem.tsx
> +            ) : null}
@zia-copods , as suggested by @arshabh-copods , we can use `&&` operator instead of ternary if we are giving boolean or expression in condition. Sharing the reference of official docs:
https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

2022-12-20 13:13 UTC, zia-copods commented on app/components/members/MemberListItem.tsx
> +          <span className="memberName flex gap-1 text-base text-gray-700">
removed `memberName` from className, I haven't found it being used in any test.

2022-12-21 08:48 UTC, yash6102000 commented on app/components/common-components/Badge.tsx
> +import { BadgeComponent } from '~/interface/Interface'
please use type....import type{..}

2022-12-21 08:48 UTC, yash6102000 commented on app/components/members/MemberListItem.tsx
> +          <span className="flex gap-1 text-base text-gray-700">
do we need both span and div?

2022-12-21 08:48 UTC, yash6102000 commented on cypress/e2e/members-test/members.cy.ts
> +    getElement.should('have.length', 1)
instead of length can we check the text on the batch?

2022-12-22 10:39 UTC, yash6102000 approved these changes

2022-12-26 07:30 UTC, richa-copods approved these changes

2022-12-28 04:47 UTC, closed without merging