update table in assessments
copods/kela-quiz pull request #509
Opened 2022-12-23 05:20 UTC by yash6102000

2022-12-28 13:18 UTC, richa-copods requested changes

2022-12-28 13:18 UTC, richa-copods commented on app/components/tests/TestList.tsx
> +  const testsColumn = [
Give proper type to `testsColumn`. Better if you rename(testColumns) it too.

2022-12-28 13:18 UTC, richa-copods commented on app/interface/Interface.tsx
> +  render?: (data: any, index: number) => JSX.Element
Give type to `data`

2023-01-03 02:48 UTC, richa-copods commented on app/components/tests/TestList.tsx
> +  const testsColumn = [
Types are not added, please add them

2023-01-03 02:55 UTC, richa-copods requested changes

2023-01-03 02:55 UTC, richa-copods commented on app/components/tests/TestList.tsx
> +    if (deleted === true) {
It can be written as `if(deleted)`

2023-01-03 02:55 UTC, richa-copods commented on app/components/tests/TestList.tsx
> +  const testColumns = [
Add types for Column

2023-01-03 02:55 UTC, richa-copods commented on app/components/tests/TestList.tsx
> +      `?index=&data=%7B"orderBy"%3A%7B"createdAt"%3A"desc"%7D%7D&TestPage=${testsCurrentPage}&TestItems=${testsPageSize}`
Use proper naming conventions for query parameters, `index`, `data` start with small case whereas `TestPage` and `TestItems` start with capital letters

2023-01-03 02:55 UTC, richa-copods commented on app/models/tests.server.ts
> +  testsCurrentPage = 5
Why currentPage is 5?

2023-01-03 04:47 UTC, yash6102000 commented on app/models/tests.server.ts
> +  testsCurrentPage = 5
it is a fallback value

2023-01-03 06:34 UTC, akshay-copods commented on app/interface/Interface.tsx
> +  render?: (data: any, index: number) => JSX.Element
In interface we are keeping render function parameter `data` type as `any` for now. In future we will update it with proper type.

2023-01-09 07:18 UTC, anuragP04 approved these changes

2023-01-13 03:10 UTC, merged