pagination-added-to-tests
copods/kela-quiz pull request #511
Opened 2022-12-26 06:52 UTC by yash6102000

2022-12-28 13:37 UTC, richa-copods requested changes

2022-12-28 13:37 UTC, richa-copods commented on app/components/sections/Sections.tsx
> +  console.log(isActive, 'isActive')
Remove consoles

2022-12-28 13:37 UTC, richa-copods commented on app/components/sections/Sections.tsx
> +  let navigate = useNavigate()
Use `const` here

2022-12-28 13:37 UTC, richa-copods commented on app/components/sections/Sections.tsx
> +    console.log('navigate')
Remove console

2022-12-28 13:37 UTC, richa-copods commented on app/models/sections.server.ts
> +  currentWorkspaceId: string | undefined
Can `currentWorkspaceId` be ever undefined?

2022-12-28 13:37 UTC, richa-copods commented on app/routes/$workspaceId/tests.tsx
> +  console.log(testCurrentPage, 'testCurrentPage')
Remove the console

2022-12-28 13:37 UTC, richa-copods commented on app/routes/$workspaceId/tests.tsx
> +  console.log(data, 'data')
Remove all the consoles

2022-12-28 13:37 UTC, richa-copods commented on app/routes/$workspaceId/tests.tsx
> +    data.selectedSectionId || data.sections[6]?.id || 'NA'
Why using 6th index?

2022-12-28 13:37 UTC, richa-copods commented on app/routes/$workspaceId/tests.tsx
> +    // data.selectedSectionId,
Remove unwanted commented code

2023-01-03 02:40 UTC, richa-copods commented on app/components/sections/Sections.tsx
> +  let navigate = useNavigate()
Resolve this

2023-01-03 02:42 UTC, richa-copods commented on app/components/sections/Sections.tsx
> +  let navigate = useNavigate()
Resolve this

2023-01-03 02:46 UTC, richa-copods requested changes

2023-01-03 02:46 UTC, richa-copods commented on app/models/sections.server.ts
> +export async function getAllTestsCounts(currentWorkspaceId?: string) {
Shouldn't passing `currentWorkspaceId` be mandatory?

2023-01-03 04:51 UTC, yash6102000 commented on app/models/sections.server.ts
> +export async function getAllTestsCounts(currentWorkspaceId?: string) {
cuz we are fetching as per active workspace/current workspace

2023-01-03 05:06 UTC, anuragP04 commented on app/models/sections.server.ts
> +export async function getAllTestsCounts(currentWorkspaceId?: string) {
Add filter parameter in count.

2023-01-03 06:42 UTC, yash6102000 commented on app/models/sections.server.ts
> +export async function getAllTestsCounts(currentWorkspaceId?: string) {
filter isn't needed

2023-01-03 06:50 UTC, richa-copods requested changes

2023-01-03 06:50 UTC, richa-copods commented on app/components/sections/Sections.tsx
> +      `?filter=%7B"orderBy"%3A%7B"createdAt"%3A"desc"%7D%7D&testPage=${testsCurrentPage}&testItems=${testsPageSize}`
Simplify the query parameters string

2023-01-03 06:50 UTC, richa-copods commented on app/routes/$workspaceId/tests.tsx
> +        action: `/${data.currentWorkspaceId}${routes.tests}/${data.sections[0].id}?filter=%7B"orderBy"%3A%7B"createdAt"%3A"desc"%7D%7D&testPage=${data.testCurrentPage}&testItems=${data.testItemsPerPa
Simplify the query parameters string

2023-01-12 02:10 UTC, anuragP04 commented on app/components/sections/Sections.tsx
> +import Pagination from '../common-components/Pagination'
![Uploading Screenshot 2023-01-12 at 7.38.23 AM.png…]()
Breaking UI

2023-01-12 02:10 UTC, anuragP04 commented on app/components/sections/Sections.tsx
![Uploading Screenshot 2023-01-12 at 7.39.06 AM.png…]()
Breaking UI

2023-01-12 02:10 UTC, anuragP04 commented on app/components/sections/Sections.tsx
>    section,
delete issue is still not fixed, if i'm on a page with single record and delete it, I am stuck with `no record found`

2023-01-19 04:34 UTC, anuragP04 commented on app/routes/$workspaceId/tests.tsx
> +    data.sections[0]?.id,
why we have added this dependency here?

2023-01-19 04:34 UTC, anuragP04 commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +      sections = res as unknown as Section[]
why unknown??

2023-01-19 04:34 UTC, anuragP04 commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +  await getAllSections('', '', currentWorkspaceId as string)
why we are not sending filters here?

2023-01-19 04:34 UTC, anuragP04 commented on app/components/sections/tests.helper.tsx
> +import { getAllSections } from '~/models/sections.server'
discuss with me regarding this file

2023-01-23 13:32 UTC, anuragP04 approved these changes

2023-01-23 13:33 UTC, merged