Update table on results page
copods/kela-quiz pull request #512
Opened 2022-12-26 15:27 UTC by akshay-copods

- Added the table component on results page
- Added the filter to filter by status ( Active, Inactive or All) 

## Preview 
<img width="832" alt="image" src="https://user-images.githubusercontent.com/117165556/209563261-45995517-6caa-4d7f-936b-31e33296081c.png">

![update_table_results](https://user-images.githubusercontent.com/117165556/209563380-984787f1-bdf8-4f10-87ca-b542ed81f2e0.gif)

2022-12-28 10:43 UTC, richa-copods requested changes

2022-12-28 10:43 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +  const otherFilters = [
Give type

2022-12-28 10:43 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +  const resultsColumn = [
Give type

2022-12-28 10:43 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +      `?ResultPage=${resultsCurrentPage}&ResultItems=${resultsPageSize}&filterByStatus=${statusFilter}`
why capital R for `ResultPage` and 'ResultItmes`. Maintain consistency in naming query parameters

2022-12-28 10:43 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
> +          {/* <div className="rounded-lg shadow-base">
Delete commented code if not needed in future

2022-12-28 10:43 UTC, richa-copods commented on cypress/e2e/group-by-test/CandidateListOfTestItem.cy.ts
> +  it('Checks, test is available for test', () => {
Correct the statement

2022-12-28 11:28 UTC, akshay-copods commented on app/components/common-components/TableComponent.tsx
> +  render?: (data: T, index: number) => any
return value can be anything `number`, `string`, etc. thats why the return type is `any`

2022-12-29 10:02 UTC, ayushicopods commented on app/components/common-components/TableComponent.tsx
> +  render?: (data: T, index: number) => any
can we use generic rather than any

2022-12-29 10:13 UTC, ayushicopods commented on app/components/common-components/SortFilter.tsx
> +import { OtherFilters, sortByOrder } from '~/interface/Interface'
use the same naming convention for the interface either pascal or camel

2022-12-29 10:18 UTC, ayushicopods commented on app/components/results/GroupByTests.tsx
>      const heading = document.getElementById('heading')
is it possible to make a generic function  in utils for getting any element from DOM.

2023-01-02 06:31 UTC, akshay-copods commented on app/components/common-components/SortFilter.tsx
> +import { OtherFilters, sortByOrder } from '~/interface/Interface'
In interface file pascal case is used so the same is used here.

2023-01-03 02:31 UTC, richa-copods commented on app/components/results/CandidateListOfTest.tsx
> +        {data.candidate.firstName && data.candidate.lastName && data.endAt ? (
Resolve this comment

2023-01-03 02:36 UTC, richa-copods requested changes

2023-01-03 02:36 UTC, richa-copods commented on app/components/results/CandidateListOfTest.tsx
> +  const column: column[] = [
Give proper name, something like "tableColumnType"

2023-01-03 10:53 UTC, richa-copods commented
Please see why test cases are failing

2023-01-03 12:38 UTC, richa-copods approved these changes

2023-01-04 07:00 UTC, merged