457 leave workspace
copods/kela-quiz pull request #525
Opened 2023-01-02 07:58 UTC by akshay-copods

- If the user is workspace owner, they are not permitted to leave the workspace.
- After leaving workspace, user will be navigated to his own workspace.

## Preview 
![leave_workspace](https://user-images.githubusercontent.com/117165556/210205949-1794a0a7-fe78-4a90-8be1-d708479f83ea.gif)

2023-01-02 09:54 UTC, yash6102000 commented on app/components/settings/Workspace.tsx
> +    submit({ addSection: 'sectionAdd' }, { method: 'post' })
can we adding section here?please rename it

2023-01-02 09:54 UTC, yash6102000 commented on app/components/settings/Workspace.tsx
> +  const loaderData = useLoaderData()
can we rename it workspaceLoaderData or workspaceData

2023-01-02 09:54 UTC, yash6102000 commented on app/components/settings/Workspace.tsx
> +            <p>{t('settings.leaveWorkspaceConfirmation')}</p>
please use span here?

2023-01-02 09:54 UTC, yash6102000 commented on app/routes/$workspaceId/settings/workspace.tsx
> +// import { redirect } from '@remix-run/node'
please remove commented code ...if not in use

2023-01-02 09:54 UTC, yash6102000 commented on app/routes/$workspaceId/settings/workspace.tsx
> +  await leaveWorkspace(workspaceId, userId)
create varibale here and return it

2023-01-02 09:54 UTC, yash6102000 commented on app/routes/$workspaceId/settings/workspace.tsx
> +  const userId = (await getUserId(request)) as string
please define loaderdata type

2023-01-02 09:54 UTC, yash6102000 commented on app/routes/$workspaceId/settings/workspace.tsx
> +  let response = null
please define actiindata types

2023-01-02 09:54 UTC, yash6102000 commented on app/routes/$workspaceId/settings/workspace.tsx
> +      if (actionData?.resp?.status === 200) {
instead if (actionData)....remove this and use optional chaining

2023-01-02 09:54 UTC, yash6102000 commented on app/routes/$workspaceId/settings/workspace.tsx
> +        navigate(`/${loaderData?.ownersWorkspace?.id}/members`)
please use const for members

2023-01-02 10:08 UTC, akshay-copods commented on app/components/settings/Workspace.tsx
> +            <p>{t('settings.leaveWorkspaceConfirmation')}</p>
Since it is a sentence, using `paragraph` tag is more appropriate.

2023-01-02 10:23 UTC, akshay-copods commented on app/routes/$workspaceId/settings/workspace.tsx
> +  await leaveWorkspace(workspaceId, userId)
server function is not returning anything so no point in creating variable.

2023-01-03 10:07 UTC, richa-copods requested changes

2023-01-04 07:58 UTC, richa-copods requested changes

2023-01-04 07:58 UTC, richa-copods commented on app/components/settings/Workspace.tsx
> +  const [openLeavePopup, setOpenLeavePopup] = useState(false)
Rename it to `showLeaveWorkspacePopup`

2023-01-05 08:53 UTC, anuragP04 approved these changes

2023-01-05 08:53 UTC, merged