WIP:529 add copy link option in candidate invite list
copods/kela-quiz pull request #537
Opened 2023-01-06 12:23 UTC by ayushicopods

2023-01-09 10:41 UTC, yash6102000 commented on app/components/TestListActionMenu.tsx
> +                          {menuItem?.menuListLink ? (
use :null instead of '' / use && check

2023-01-09 10:41 UTC, yash6102000 commented on app/components/results/CandidateListOfTest.tsx
> +    toast.success('Link Copied')
can we use constant here?

2023-01-09 14:52 UTC, ayushicopods commented on app/components/results/CandidateListOfTest.tsx
> +    toast.success('Link Copied')
i have resolved it

2023-01-09 14:54 UTC, ayushicopods commented on app/components/TestListActionMenu.tsx
> +                          {menuItem?.menuListLink ? (
In some cases may be we don't want icons that's why I used ternary operator

2023-01-10 11:05 UTC, yash6102000 commented on app/components/TestListActionMenu.tsx
> +                          {menuItem?.menuListLink ? (
... can u please try once....

2023-01-12 09:25 UTC, yash6102000 requested changes

2023-01-12 09:25 UTC, yash6102000 commented on app/components/TestListActionMenu.tsx
> +                          menuItem.onClickOfButton && menuItem.onClickOfButton()
can we rename it as a menuActionButton?

2023-01-12 09:25 UTC, yash6102000 commented on app/components/results/CandidateListOfTest.tsx
> +      (e) => toast.error(`Fail ${e}`)
please add Fail in index file also

2023-01-12 09:25 UTC, yash6102000 commented on app/components/results/CandidateListOfTest.tsx
> +          resendInvite(data.id, data.candidateId, data.testId),
same rename as above

2023-01-12 09:25 UTC, yash6102000 commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +    cy.get('#vertical-icon', { timeout: 8000 }).click()
please remove timeout of 8000 and set 6000 also do this to avoid failure..
cy.get('#vertical-icon', { timeout: 6000 }).should('be.visible')
cy.get('#vertical-icon', { timeout: 6000 }).click()
in this way assertion also not missed

2023-01-12 09:25 UTC, yash6102000 commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +    cy.get('#vertical-icon', { timeout: 8000 }).click()
same here

2023-01-12 11:05 UTC, yash6102000 requested changes

2023-01-12 11:05 UTC, yash6102000 commented on app/components/TestListActionMenu.tsx
> +          <Menu.Items className="absolute right-6 z-40  origin-bottom-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5">
<img width="1356" alt="Screenshot 2023-01-12 at 4 34 47 PM" src="https://user-images.githubusercontent.com/107238610/212050571-97f2e6d0-c054-4d09-a6ff-2333591c54b3.png">
please make sure that card is not covering 3dots menu icons

2023-01-13 03:16 UTC, anuragP04 approved these changes

2023-01-13 12:04 UTC, anuragP04 approved these changes

2023-01-19 09:08 UTC, merged