Result Details: section wise result
copods/kela-quiz pull request #542
Opened 2023-01-09 13:41 UTC by yash6102000

have to show questions detail answered by candidate by section

2023-01-26 18:09 UTC, anuragP04 commented on helper/results.helper.ts
> +export function areEqual(textAnswer: any, correctAnswersArray: any) {
change the name of function

2023-01-26 18:37 UTC, anuragP04 commented on helper/members.helper.tsx
>  ) => {
why do we have change in this file?

2023-02-02 13:28 UTC, richa-copods requested changes

2023-02-02 13:28 UTC, richa-copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  const correctOrder = textAnswer.map(
Share the structure for all the scenarios in document form

2023-02-02 13:28 UTC, richa-copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +        {status === 'ANSWERED' && (
Create ENUM for status

2023-02-02 13:28 UTC, richa-copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +
Format file

2023-02-02 13:28 UTC, richa-copods commented on app/models/assessment.server.ts
> +            (textAnswer: any, index: number) => {
Give proper type. Avoid using any

2023-02-02 13:28 UTC, richa-copods commented on helper/results.helper.ts
> +export function areEqualArrays(textAnswer: any, correctAnswersArray: any) {
Give proper type

2023-02-02 13:28 UTC, richa-copods commented on helper/results.helper.ts
> +  let N = textAnswer.length
Give proper names to variables

2023-02-09 12:48 UTC, richa-copods requested changes

2023-02-09 12:48 UTC, richa-copods commented on app/components/results/ResultDetailBySections.tsx
> +import { useLoaderData, useNavigate } from "@remix-run/react"
Resolve ESLint warnings

2023-02-09 12:48 UTC, richa-copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +import { areEqualArrays } from "helper/results.helper"
Resolve ESLint warnings

2023-02-09 12:48 UTC, richa-copods commented on app/interface/Interface.tsx
> +  question: any
Add proper type. Avoid using `any`

2023-02-09 12:48 UTC, richa-copods commented on app/models/assessment.server.ts
>        if (question?.question?.questionType?.value === "TEXT") {
use ENUM `QuestionTypes`

2023-02-09 12:48 UTC, richa-copods commented on app/models/assessment.server.ts
> +        if (checkOrder === true) {
Simplify it to `if(checkOrder)`

2023-02-09 12:48 UTC, richa-copods commented on app/models/assessment.server.ts
> +        if (checkOrder === false) {
Use else

2023-02-09 12:48 UTC, richa-copods commented on app/models/assessment.server.ts
>        } else if (question?.question?.questionType?.value === "SINGLE_CHOICE") {
Use ENUM `QuestionTypes`

2023-02-09 12:48 UTC, richa-copods commented on helper/results.helper.ts
> +  // array are not equal
Answers are not equal

2023-02-09 12:48 UTC, richa-copods commented on public/locales/en/index.json
> +    "viewDetails": "View details",
Capitalise D of `details`

2023-02-09 12:48 UTC, richa-copods commented on public/locales/en/index.json
> +    "givenAnswers": "Given answers",
Capitalise a of `answers`

2023-02-09 12:48 UTC, richa-copods commented on public/locales/en/index.json
> +    "unordered": "unordered",
Capitalise u of `unordered`

2023-02-10 06:40 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +  let navigate = useNavigate()
We won't be resigning navigate to anything else so using const here seems more promising

2023-02-10 06:41 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +            role={"button"}
Remove extra gap after gap-4 and remove the {} in role as we can use string directly

2023-02-10 06:42 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +            ></Icon>
This can be a self-closing tag

2023-02-10 06:58 UTC, Dhruv-Copods commented on app/routes/$workspaceId/results/groupByTests/$testId.$candidateId.$sectionId.tsx
> +    </div>
ResultDetailBySections already has a Div wrapper why are we adding additional div over here

2023-02-10 07:05 UTC, Dhruv-Copods commented on app/routes/$workspaceId/results/groupByTests/$testId.$candidateId.$sectionId.tsx
> +    </div>
Or convert it into a fragment

2023-02-10 07:07 UTC, anuragP04 requested changes

2023-02-10 07:07 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +            </div>
**I'm not adding more comments in this, please refactor all based on above comments**

2023-02-13 07:27 UTC, Dhruv-Copods commented on app/components/common-components/Chip.tsx
> +const Chip = ({ text, variant }: { text: string; variant: any }) => {
Remove any type of variant

2023-02-13 09:11 UTC, Dhruv-Copods commented on app/components/common-components/Chip.tsx
> +      case "sucess":
Typo of success

2023-02-13 09:16 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +            className="flex items-center gap-4 "
extra space after last class

2023-02-13 09:17 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +            </h1>
Why does 2 different elements have the same id

2023-02-13 09:23 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +    if (textAnswerArrayLength != correctAnswersArrayLength) return false
Add strict type checking

2023-02-13 09:24 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +      if (textAnswer[i] != (correctAnswersArray[i] as unknown as CorrectAnswer))
Add strict type checking

2023-02-13 09:25 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +    <div className="flex w-full  rounded-lg  border border-gray-300 bg-white">
extra space after and before rounded-lg class

2023-02-13 09:25 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +          className="question flex-1   flex-row"
extra space before flex-row

2023-02-13 09:28 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                <Chip text={t("resultConstants.correct")} variant={"sucess"} />
if checkOrder will only return a boolean we dont need to compair it with true or false, directly use the variable, same goes for flag.includes() we can use ! for false

2023-02-13 09:28 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +              {questionType.value == QuestionTypes.text
Add strict type checking

2023-02-13 09:30 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                  correctAnswer.map(
checkOrder and orderFlag can be directly used if they will only return booleans

2023-02-13 09:31 UTC, Dhruv-Copods commented on app/models/assessment.server.ts
> +        let correctOrder
we can declare correctOrder as []

2023-02-13 09:33 UTC, Dhruv-Copods commented on app/models/assessment.server.ts
> +            let correctFlag = true
avoid using same variable names in single function even if function scope allows us to do it, reader can misinterpret where this value is being stored

2023-02-13 11:55 UTC, anuragP04 requested changes

2023-02-13 11:55 UTC, anuragP04 commented on app/models/assessment.server.ts
> +        if (checkOrder) {
can you optimize this function

2023-02-13 11:56 UTC, anuragP04 commented
Please do the discussed changes

2023-02-13 12:06 UTC, anuragP04 requested changes

2023-02-13 12:06 UTC, anuragP04 commented on app/components/common-components/Chip.tsx
> +  const variantMap: any = {
remove any

2023-02-14 16:26 UTC, Dhruv-Copods commented on app/components/common-components/Chip.tsx
> +      className={`rounded-full px-4 py-2 text-xs font-medium ${variantMap[variant]} text-${variantMap[variant]}-800 `}
we updated varientMap for bg color but what about text, the text classname needs to be updated as well

2023-02-14 16:29 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +            }}
can be converted into, e.key === "Enter" && navigate()

2023-02-14 16:30 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +            }}
both navigate are using rame route why not create a const variable at the top to hold this navigation route, so if in future we have to update it , it will be easier for us

2023-02-14 16:31 UTC, Dhruv-Copods commented on app/components/results/ResultDetailBySections.tsx
> +              {sectionDetail.candidateTest?.candidate?.lastName}
Better to write it as, {`${sectionDetail.candidateTest?.candidate?.firstName} ${sectionDetail.candidateTest?.candidate?.lastName}`}.
So we can avoid the {" "}

2023-02-14 16:33 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  function areEqualAsnwersArray(
typo of word answers

2023-02-14 16:35 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  function mcqFlag() {
this feels more like a state name than function name, please update function name

2023-02-14 16:36 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +            {t("candidateExamConstants.question")} {index}
convert this into {`${t("candidateExamConstants.question")} ${index}`}

2023-02-14 16:40 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +              (checkOrder === false &&
use !checkOrder

2023-02-14 16:41 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +              (checkOrder === false &&
use !checkOrder

2023-02-14 16:46 UTC, Dhruv-Copods commented on app/models/assessment.server.ts
> +              if (correctAnswers[i].localeCompare(userAnswers[i]) != 0) {
add strict type checking

2023-02-16 05:36 UTC, anuragP04 requested changes

2023-02-16 05:36 UTC, anuragP04 commented on cypress/e2e/group-by-test/groupByTestTable.cy.ts
> +    getGroupByItems().eq(1).should("have.text", test1)
what is this eq(1) ?

2023-02-16 05:36 UTC, anuragP04 commented on app/models/assessment.server.ts
> +  if (otp === Number("0000")) {
why you have removed this check?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  function checkMaq() {
What is this Maq?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
why we have disabled eslint for this function?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
why we have disabled eslint for this function?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  const correctAnswersArray = correctAnswer.map(
defining this variable here and using it in function defined above this line....why?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +        setFlag(true)
why you are setting the flag to true everytime?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +            <Chip text={""} variant={""} />
why we have this empty chip here?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +              {questionType.value === QuestionTypes.text ? (
why are you sending empty variant to chip?

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                <Chip text={t("resultConstants.text")} variant={""} />
same as above

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                  <Chip text={t("sectionsConstants.msq")} variant={""} />
same as above

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                <Chip text={t("sectionsConstants.mcq")} variant={""} />
same as above

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                  <Chip text={t("sectionsConstants.msq")} variant={""} />
you have assigned wrong constant here

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                <Chip text={t("sectionsConstants.mcq")} variant={""} />
you have assigned wrong constant here

2023-02-16 05:36 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +  const [flag, setFlag] = useState(false)
we can have some more verbose naming for this.

2023-02-16 05:38 UTC, anuragP04 requested changes

2023-02-16 05:38 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +                      key={index}
avoid using index as key

2023-02-16 06:52 UTC, yash6102000 commented on app/models/assessment.server.ts
> +import { QuestionTypes } from "~/interface/Interface"
this is enum

2023-02-17 08:58 UTC, anuragP04 approved these changes

2023-02-17 08:59 UTC, merged