[WIP]feat(): delete_question_scenarios
copods/kela-quiz pull request #559
Opened 2023-01-24 18:19 UTC by yash6102000

2023-01-26 18:39 UTC, anuragP04 commented on app/components/common-components/DeletePopUp.tsx
>    deleteItemType,
why do we have change in this file?

2023-01-26 18:39 UTC, anuragP04 commented on app/components/sections/QuestionCard.tsx
> +    // candidateQuestion?: CandidateQuestion[]
remove commented code

2023-01-26 18:39 UTC, anuragP04 commented on app/components/sections/QuestionCard.tsx
> +  }
why do we have extra lines added here?

2023-01-26 18:39 UTC, anuragP04 commented on app/components/sections/SectionDetails.tsx
>    const { t } = useTranslation()
why do we have change in this file

2023-01-27 05:21 UTC, ayushicopods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +  console.log(section, 'section')
remove console

2023-01-31 06:35 UTC, anuragP04 commented on app/models/sections.server.ts
> +  const getQuestion = await prisma.question.findUnique({
variable name is getQuestion???

2023-01-31 06:35 UTC, anuragP04 commented on app/models/sections.server.ts
> +  const sortTotalTime = totalQuestionArray?.sort((a: any, b: any) => {
avoid using any

2023-01-31 06:35 UTC, anuragP04 commented on app/models/sections.server.ts
> +  const sortTotalTime = totalQuestionArray?.sort((a: any, b: any) => {
why we are using time here to compare?

2023-02-02 11:23 UTC, richa-copods requested changes

2023-02-02 11:23 UTC, richa-copods commented on app/models/sections.server.ts
> +  console.log(totalQuestionArray, 'totalQuestionArray')
Remove console

2023-02-02 11:23 UTC, richa-copods commented on app/models/sections.server.ts
> +    (data: any) => {
Give proper type. Avoid using any

2023-02-02 11:23 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
>    if (action === 'deleteQuestion') {
Use enum for action

2023-02-02 11:23 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    if ((section && (section as string)) === 'success') {
Write condition properly. This is not standard.

2023-02-02 11:23 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    } else if ((section && (section as string)) === 'not deleted') {
Write condition properly. This is not standard.

2023-02-02 11:23 UTC, richa-copods commented on public/locales/en/index.json
> +    "testMayAffectWarning": "This question is being used in a test, further invites will not get this question.",
Use existing message of "Deleted Successfully..!". No need of this

2023-02-02 11:23 UTC, richa-copods commented on public/locales/en/index.json
> +    "questionNotDeleted": "Cannot delete question. This test is used in assessment and will cause conflict after deleting."
Test can not be deleted as being used in existing Assessment.

2023-02-03 11:21 UTC, richa-copods requested changes

2023-02-03 11:21 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
> +  }
@yash6102000 acknowledge this please

2023-02-03 11:21 UTC, richa-copods commented on app/components/sections/SectionDetails.tsx
>    const { t } = useTranslation()
@yash6102000 acknowledge this please

2023-02-03 11:21 UTC, richa-copods commented on app/models/sections.server.ts
> +  return deleteQuestion && 'success'
Return simple `true` or `false`

2023-02-07 10:36 UTC, richa-copods requested changes

2023-02-07 10:36 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    if (section === true) {
use condition `if(section)`

2023-02-07 10:36 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    } else if (section === false) {
use `else` instead of `else if`

2023-02-07 10:36 UTC, richa-copods commented on public/locales/en/index.json
> +    "questionNotDeleted": "Test can not be deleted as being used in existing Assessment."
change to "Question cannot be deleted..."

2023-02-09 10:46 UTC, anuragP04 commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +    } else if (section === false) {
@yash6102000 , please resolve this comment, it is not resolved yet. If you have any doubts or need clarity please let us know.

2023-02-09 10:47 UTC, richa-copods requested changes

2023-02-09 10:47 UTC, richa-copods commented on app/components/sections/QuestionCard.tsx
>  import { useTranslation } from "react-i18next"
Resolve all the ESLint warnings

2023-02-10 06:39 UTC, richa-copods requested changes

2023-02-10 06:39 UTC, richa-copods commented on app/models/sections.server.ts
> +      return "not deleted"
Hey change it to "notDeleted". And better if you create ENUM for this

2023-02-10 06:56 UTC, richa-copods requested changes

2023-02-10 06:56 UTC, richa-copods commented on app/interface/Interface.tsx
> +  questionNotDeleted = "QUESTION_NOT_DELETED",
You can simply keep it as `notDeleted = NOT_DELETED`, as ENUM specifies it is status for delete question

2023-02-10 06:56 UTC, richa-copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +        toastId: "sectionsConstants.questionNotDeleted",
Give proper toastId.

2023-02-10 08:47 UTC, richa-copods requested changes

2023-02-10 08:47 UTC, richa-copods commented on app/models/sections.server.ts
> +  const totalQuestionArray = questionData?.section?.sectionInTest.map(
Rename it to totalQuestionsList

2023-02-10 11:41 UTC, merged