Bug fixes
copods/kela-quiz pull request #60
Opened 2022-08-24 07:20 UTC by yash6102000

2022-08-25 10:57 UTC, arpita-20 requested changes

2022-08-25 10:57 UTC, arpita-20 commented on app/components/results/AttendedCandidateListItem.tsx
> +        className="col-span-full grid grid-cols-12 gap-3 border-t-[1px] border-solid border-[#E5E7EB] bg-white px-12 py-4"
remove hard coded value

2022-08-25 10:57 UTC, arpita-20 commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +        toast.error('Select the Correct Option', {
add 'select the correct option' in  common constant file

2022-08-25 10:57 UTC, arpita-20 commented on app/components/sections/add-question/AddQuestionInSection.tsx
> +        toast.error('Select the Correct Option', {
add 'select the correct option' in common constant file

2022-08-25 10:57 UTC, arpita-20 commented on app/components/sections/add-question/OptionForQuestion.tsx
> +        return toast.error('you can add maximum six options only.', { toastId })
add this in common constant file

2022-08-25 11:10 UTC, richa-copods submitted a review, later dismissed

2022-09-01 10:27 UTC, anuragP04 approved these changes

2022-09-01 10:27 UTC, merged