Bug fixes for results
copods/kela-quiz pull request #62
Opened 2022-08-25 10:23 UTC by arpita-20

Bug fixes for results page-

1-While deleting test on test page ,that particular test is not being
 deleted on results page 
 solution-added status column to keep track of the test page 
 2-For one Email id ,only one link should be generated
solution-fixed this bug and also added toast for this error

2022-08-25 11:22 UTC, richa-copods requested changes

2022-08-25 11:22 UTC, richa-copods commented on app/components/tests/InviteCandidatePopup.tsx
> +      actionData?.candidateInviteStatus == candidateExam.candidateTestCreated
Please use strict check `===`

2022-08-25 11:22 UTC, richa-copods commented on app/constants/common.constants.ts
> +  noCandidateForTest: 'No Candidate for this Test',
Please change the text to- `No candidate has attempted this test`

2022-08-25 11:22 UTC, richa-copods commented on app/constants/common.constants.ts
> +  errorOfcreateCandidateTest: 'errorOfcreateCandidateTest',
Please remove if not being used

2022-08-25 11:22 UTC, richa-copods commented on app/components/results/GroupByTests.tsx
>                <span className="col-span-1 text-sm font-semibold  text-gray-500">
Please remove extra space

2022-08-25 11:26 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
>          <div className=" col-span-1 truncate">
remove extra space.

2022-08-25 11:26 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
>            <span className=" text-base leading-6 text-gray-700">{index}</span>
remove extra space.

2022-08-25 11:26 UTC, anuragP04 commented on app/components/results/GroupByTestItems.tsx
>            {candidateTests.candidateTest?.length}
candidateTests.candidateTest ??

create object such that these structure can be avoided or if it contains more information then update prop name

2022-08-25 11:26 UTC, anuragP04 commented on app/components/results/GroupByTests.tsx
>                  {resultConstants.srno}
use camelCase for variable names

2022-08-25 11:26 UTC, anuragP04 commented on app/components/results/GroupByTests.tsx
>              <div id="GroupByTestItems" className="col-span-10 grid">
use camelCase or kebab-case for ID, don't use PascalCase for ID naming, preferred: kebab-case

2022-08-25 11:26 UTC, anuragP04 commented on app/components/tests/InviteCandidatePopup.tsx
> +import { candidateExam, testsConstants } from '~/constants/common.constants'
we can make constants group/objects name more consistant, in one we are using Constant and in other not.

2022-08-25 11:26 UTC, anuragP04 commented on app/constants/common.constants.ts
>    srno: 'Sr.No',
use camelCase

2022-08-25 11:26 UTC, anuragP04 commented on app/constants/common.constants.ts
>  export const cypress = {
try to reduce the constants inside cypress, we don't need this one

2022-08-25 11:26 UTC, anuragP04 commented on app/models/candidate.server.ts
>      throw new Error('Candidate Create Error..!')
use constants

2022-08-25 11:26 UTC, anuragP04 commented on app/models/candidate.server.ts
>      throw new Error('Candidate Test Create Error..!')
use constant here

2022-08-25 18:53 UTC, yash6102000 commented on app/components/results/GroupByTestItems.tsx
> +        <div className="col-span-2 text-base leading-6 text-gray-700">
no need to add leading class if we r using font size classes provided by tailwind

2022-08-25 18:53 UTC, yash6102000 commented on app/components/results/GroupByTestItems.tsx
>            <span className=" text-base leading-6 text-gray-700">{index}</span>
no need to add leading class if we r using font size classes provided by tailwind

2022-08-25 18:53 UTC, yash6102000 commented on app/components/results/GroupByTestItems.tsx
>          <div className="col-span-2 truncate text-base leading-6 text-gray-700">
no need to add leading class if we r using font size classes provided by tailwind

2022-08-25 18:53 UTC, yash6102000 commented on app/components/results/GroupByTestItems.tsx
> +          } col-span-1 text-base leading-6`}
no need to add leading class if we r using font size classes provided by tailwind

2022-09-01 10:45 UTC, anuragP04 approved these changes

2022-09-01 10:46 UTC, merged