601 result page getting incorrect data
copods/kela-quiz pull request #644
Opened 2023-02-07 07:22 UTC by Dhruv-Copods

2023-02-09 10:32 UTC, richa-copods requested changes

2023-02-09 10:32 UTC, richa-copods commented on app/context/Common.context.tsx
> +      return storage.find((store) => store.key === key)
create another function for get

2023-02-13 06:05 UTC, richa-copods approved these changes

2023-02-13 06:27 UTC, anuragP04 approved these changes

2023-02-13 06:27 UTC, merged