refactor: test
copods/kela-quiz pull request #653
Opened 2023-02-09 10:36 UTC by yash6102000

2023-02-09 18:53 UTC, anuragP04 requested changes

2023-02-09 18:53 UTC, anuragP04 commented on app/services/tests.service.ts
> +export const getALLUsers = async (currentWorkspaceId: string) => {
same as above

2023-02-09 18:53 UTC, anuragP04 commented on app/services/tests.service.ts
> +export const getALLTest = async (currentWorkspaceId: string) => {
same as above, also, use section keyword here, it will create confusion for devs.

2023-02-10 11:49 UTC, anuragP04 requested changes

2023-02-10 11:49 UTC, anuragP04 commented on app/routes/$workspaceId/tests/index.tsx
> +  const users = await getAllUsersData(currentWorkspaceId)
why you have updated argument type?

2023-02-13 09:42 UTC, Dhruv-Copods commented on app/routes/$workspaceId/tests/$sectionId.tsx
> +  return deleteQuestion
we can write "return await getDeleteQuestionById()" rather than creating a variable to store the resp

2023-02-13 09:44 UTC, Dhruv-Copods commented on app/services/tests.service.ts
> +  cb: any
Remove any type

2023-02-13 09:46 UTC, Dhruv-Copods commented on app/services/tests.service.ts
> + * @param param0
@param param0 ?

2023-02-13 09:48 UTC, Dhruv-Copods commented on app/services/tests.service.ts
> +  return deleteQuestion
Directly return deleteQuestionById

2023-02-13 12:14 UTC, anuragP04 approved these changes

2023-02-13 12:14 UTC, merged