578 add assessment test list is incorrect new
copods/kela-quiz pull request #670
Opened 2023-02-13 05:54 UTC by ayushicopods

2023-02-13 06:07 UTC, Dhruv-Copods commented on app/components/tests/AddTest.tsx
> +        AllSelectedSections
As this is a array the check should be for length rather than the array itself

2023-02-13 06:09 UTC, Dhruv-Copods commented on app/components/tests/AddTest.tsx
> +        if (AllSelectedSections) {
Check of length here also

2023-02-13 06:13 UTC, Dhruv-Copods commented on app/components/tests/CreateSelectSections.tsx
> +  const fetcher: any = useFetcher()
Remix will provide type for fetcher use that

2023-02-13 09:50 UTC, Dhruv-Copods commented on app/components/tests/CreateSelectSections.tsx
Configure EsLint and save the file again, remove this error

2023-02-13 09:51 UTC, Dhruv-Copods commented on app/components/tests/CreateSelectSections.tsx
> +      let sortedData = data.sections
See if this EsLint error cna be resolved

2023-02-14 16:11 UTC, Dhruv-Copods commented on app/components/tests/AddTest.tsx
> +  // let allSelectedSections: Array<TestSection> = []
remove commented code

2023-02-14 16:12 UTC, Dhruv-Copods commented on app/components/tests/AddTest.tsx
> +          allSelectedSections.map((selected: any) => {
use forEach if not returning anything from map

2023-02-14 16:14 UTC, Dhruv-Copods commented on app/components/tests/AddTest.tsx
> +              selected[targetData]
What is this else exactly doing, as eslint error is saying there is no assignment here so we don't need this else

2023-02-14 16:16 UTC, Dhruv-Copods commented on app/components/tests/CreateSelectSections.tsx
> +  let paginationSizeOptions = [3, 6, 12, 18, 24]
I dont think we are going to reassign paginationSizeOptions anywhere else so we can use const instead of let here

2023-02-14 16:18 UTC, Dhruv-Copods commented on app/components/tests/CreateSelectSections.tsx
> +    }
We can combine both if statements as we are not writing else for any of them

2023-02-14 16:20 UTC, Dhruv-Copods commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +  )
Why are we calling getAllTestsData? we are calling a function starting with get and storing it anywhere

2023-02-14 16:21 UTC, Dhruv-Copods commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +  }
can be a const function

2023-02-14 19:56 UTC, yash6102000 commented on app/components/tests/AddTest.tsx
> +  const updateSection = (data: AddedSectionDetails, i: number) => {
make it index instead of i

2023-02-14 19:56 UTC, yash6102000 commented on app/components/tests/CreateSelectSections.tsx
> +  setSections: (e: AddedSectionDetails, i: number) => void
same as above

2023-02-14 19:56 UTC, yash6102000 commented on app/components/tests/CreateSelectSections.tsx
> +      sortedData = sortedData.map((section: TestSection) => {
variable and the data your are mapping is same?..please change

2023-02-14 20:06 UTC, yash6102000 commented on app/components/tests/CreateSelectSections.tsx
>              {sections.map((section: TestSection & { count?: number }, i) => {
make it index

2023-02-14 20:06 UTC, yash6102000 commented on app/interface/Interface.tsx
> +  isSelected: boolean | undefined
boolean is either true or false ... why it's undefined

2023-02-14 20:06 UTC, yash6102000 commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +  getAllSectionsCount: number
give return type Awaited<ReturnType<typeof getAllSectionCount>>

2023-02-14 20:06 UTC, yash6102000 commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +  const sortBy = query.get("sortBy") as string
can we give the fallback?

2023-02-14 20:06 UTC, yash6102000 commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +    JSON.parse(data as string)
either parse it first or inside the function istead of here

2023-02-14 20:06 UTC, yash6102000 commented on app/services/tests.service.ts
> +export type formData = {
can you rename it to createTestData or any other name as u think sounds good instead of formData

2023-02-17 10:32 UTC, yash6102000 requested changes

2023-02-17 10:32 UTC, yash6102000 commented on app/components/tests/CreateSelectSections.tsx
> +            pageSizeOptions={paginationSizeOptions}
instead of creating the variable , can we pass it directly here?

2023-02-17 10:32 UTC, yash6102000 commented on app/components/tests/SelectSectionCard.tsx
> +import type { AddedSectionDetails, TestSection } from "~/interface/Interface"
can we rename this interface as addSectionCard?

2023-02-17 10:32 UTC, yash6102000 commented on app/routes/$workspaceId/assessments.add-assessment.tsx
> +      totalSections={testData.getAllSectionsCount}
can we rename it totalSectionCount

2023-02-17 10:32 UTC, yash6102000 commented on app/services/tests.service.ts
> +export const getCreateTest = async (
we are creating the test here right , then we name it as get...please rename it like createTestData

2023-02-17 10:32 UTC, yash6102000 commented on app/services/tests.service.ts
> +
add the comment above as we follow in above function like what are the params and what this function is returning

2023-02-22 11:42 UTC, Dhruv-Copods commented on app/components/common-components/Pagination.tsx
>                ? " rounded-md bg-gray-200"
remove extra space

2023-02-24 06:08 UTC, Dhruv-Copods commented on app/components/common-components/Pagination.tsx
>                ? totalItems
We can use ` here to  simplify these lines

2023-02-24 10:03 UTC, anuragP04 approved these changes

2023-02-24 10:04 UTC, merged