[WIP] 676 mention length of test in email to candidate
copods/kela-quiz pull request #694
Opened 2023-02-17 09:48 UTC by Dhruv-Copods

2023-02-20 13:39 UTC, richa-copods requested changes

2023-02-20 13:39 UTC, richa-copods commented on app/models/candidate.server.ts
> +          (timeInHoursAndMinutes.h < 2 ? "Hour" : "Hours")
Possible values for Hours can be natural numbers, so can directly keep check for 1 instead of checking `timeInHoursAndMinutes.h < 2`

2023-02-20 13:39 UTC, richa-copods commented on app/models/candidate.server.ts
> +    } ${timeInHoursAndMinutes.m ? timeInHoursAndMinutes.m + "Minutes" : ""}`
What if total minutes is 1, in that case you should show "Minute" not "Minutes"

2023-02-20 13:39 UTC, richa-copods commented on app/models/candidate.server.ts
> +  const getFormatedTime = () => {
You can create a separate function for this task which takes the array of sections as parameter. This way you won't have to write same thing thrice.

2023-02-20 13:39 UTC, richa-copods commented on app/models/candidate.server.ts
> +    const testTimeArr = getUserTestTime?.sections
Please give proper name, test in `testTimeArr` and sections in `getUserTestTime?.sections` doesn't match . Feel free to replay in thread if you have justification for this.

2023-02-20 13:47 UTC, richa-copods commented
Test cases are failing, look into it.

2023-02-20 15:27 UTC, Dhruv-Copods commented on app/models/candidate.server.ts
> +          (timeInHoursAndMinutes.h < 2 ? "Hour" : "Hours")
`timeInHoursAndMinutes.h < 2` updating this to `timeInHoursAndMinutes.h <= 1`

2023-02-20 15:29 UTC, Dhruv-Copods commented on app/models/candidate.server.ts
> +    } ${timeInHoursAndMinutes.m ? timeInHoursAndMinutes.m + "Minutes" : ""}`
Didn't think we will have a test with just 1 min so didn't add the check, but will add it as a edge case

2023-02-21 12:49 UTC, richa-copods approved these changes

2023-02-21 17:12 UTC, anuragP04 requested changes

2023-02-21 17:12 UTC, anuragP04 commented on app/models/cron.server.ts
> +  cron.schedule("0 * * * *", async function () {
why the cron scheduler time has been changed?

2023-02-21 17:12 UTC, anuragP04 commented on app/models/candidate.server.ts
> +      candidate: {
do we need candidate here?

2023-02-21 17:12 UTC, anuragP04 commented on app/models/candidate.server.ts
> +        getFormatedTime(
are you sure this function won't take much time and undefined will not go there?

2023-02-21 17:14 UTC, Dhruv-Copods commented on app/models/cron.server.ts
> +  cron.schedule("0 * * * *", async function () {
both of the options act the same but saw the 2nd option as the best practice on https://crontab.guru/ so decided to update the scheduling string

2023-02-21 17:16 UTC, Dhruv-Copods commented on app/models/candidate.server.ts
> +      candidate: {
yes we need the email of the candidate in order to send the request again

2023-02-21 17:19 UTC, Dhruv-Copods commented on app/models/candidate.server.ts
> +        getFormatedTime(
typescript insists that this might come as undefined so i had to add as string at the end

2023-02-21 17:24 UTC, anuragP04 commented on app/models/cron.server.ts
> +  cron.schedule("0 * * * *", async function () {
Cool, but both are not same actually

2023-02-21 17:24 UTC, anuragP04 commented on app/models/candidate.server.ts
> +        getFormatedTime(
I am asking about the function that u have used here

2023-02-22 05:13 UTC, anuragP04 approved these changes

2023-02-22 05:13 UTC, merged