fix: removed onSelectedSectioncChange prop from test details
copods/kela-quiz pull request #700
Opened 2023-02-21 10:17 UTC by ayushicopods

2023-02-21 13:06 UTC, richa-copods approved these changes

2023-02-21 17:14 UTC, anuragP04 requested changes

2023-02-23 05:16 UTC, Dhruv-Copods commented on app/components/tests/CreateTestPreview.tsx
> +      selectedSections[action == "up" ? index - 1 : index + 1] = temp
Add strict checking

2023-02-23 05:16 UTC, Dhruv-Copods commented on app/components/tests/CreateTestPreview.tsx
> +                            i == 0 ? "cursor-not-allowed" : "cursor-pointer"
add strict checking

2023-02-23 05:17 UTC, Dhruv-Copods commented on app/components/tests/CreateTestPreview.tsx
> +                            i == selectedSections.length - 1
add strict checking

2023-02-23 05:24 UTC, yash6102000 commented on app/components/tests/CreateTestPreview.tsx
> +                              changeSelectedSectionsOrder(i, "up")
can we rename i to index?

2023-02-23 09:36 UTC, anuragP04 approved these changes

2023-02-23 09:46 UTC, merged