664 add context to assessment route
copods/kela-quiz pull request #701
Opened 2023-02-21 11:05 UTC by Dhruv-Copods

2023-02-21 13:14 UTC, richa-copods commented
Fix test cases

2023-02-21 13:14 UTC, richa-copods requested changes

2023-02-21 13:14 UTC, richa-copods commented on app/components/tests/TestList.tsx
> +    setCustomStorage("assessmentSort", sortBy)
Confirm if multiple re-renders are happening or not

2023-02-21 13:34 UTC, richa-copods approved these changes

2023-02-21 17:15 UTC, anuragP04 requested changes

2023-02-21 17:15 UTC, anuragP04 commented on app/context/Common.context.tsx
> +  setCustomStorage: (key: string, value?: any) => void
why we have this change here?

2023-02-21 17:15 UTC, anuragP04 commented on app/components/tests/TestList.tsx
> +  }, [sortBy])
try to remove this warning

2023-02-21 17:18 UTC, Dhruv-Copods commented on app/context/Common.context.tsx
> +  setCustomStorage: (key: string, value?: any) => void
as we have discussed there can be multiple type of storage values so giving any specific type here is not possible, thats why I have updated the type

2023-02-21 17:19 UTC, Dhruv-Copods commented on app/components/tests/TestList.tsx
> +  }, [sortBy])
removing the warning will cause react to rerender multiple times, so if we fix the dependency we will multiple rerenders

2023-02-21 17:25 UTC, anuragP04 commented on app/components/tests/TestList.tsx
> +  }, [sortBy])
for use effect warning, add lint comment to ignore this one then, but before that check all alternatives

2023-02-21 17:44 UTC, Dhruv-Copods commented on app/components/tests/TestList.tsx
> +  }, [sortBy])
sure

2023-02-22 07:22 UTC, anuragP04 approved these changes

2023-02-22 07:22 UTC, merged