709 featrole based access control create a feature branch and add permissions objects and functions
copods/kela-quiz pull request #719
Opened 2023-02-27 12:47 UTC by Dhruv-Copods

Added function to validate features on backend side and on frontend side

2023-02-28 11:14 UTC, richa-copods requested changes

2023-02-28 11:14 UTC, richa-copods commented on app/models/authorization.server.ts
> +  console.log(
Remove consoles

2023-02-28 12:33 UTC, richa-copods approved these changes

2023-03-01 06:02 UTC, anuragP04 approved these changes

2023-03-01 06:02 UTC, merged