727 result details is not working perfectly
copods/kela-quiz pull request #735
Opened 2023-02-28 12:22 UTC by ayushicopods

2023-03-01 06:18 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +    correctAnswers: any,
Please add valid types

2023-03-01 06:19 UTC, Dhruv-Copods commented on app/components/results/ResultDetailsQuestionsPreview.tsx
>    }, [])
add eslint exception if not going to add dependency

2023-03-02 04:51 UTC, anuragP04 requested changes

2023-03-02 04:51 UTC, anuragP04 commented on app/components/results/ResultDetailsQuestionsPreview.tsx
> +import type { Option, QuestionType, CorrectAnswer } from "~/interface/Interface"
I'm still getting same response, nothing fixed

2023-03-03 11:48 UTC, anuragP04 approved these changes

2023-03-03 11:48 UTC, merged