711 apply access checks for results
copods/kela-quiz pull request #741
Opened 2023-03-02 07:08 UTC by Dhruv-Copods

Added backend checks for result features

2023-03-02 11:52 UTC, richa-copods requested changes

2023-03-02 11:52 UTC, richa-copods commented on app/routes/$workspaceId/results/groupByTests/$testId.$candidateId.$sectionId.tsx
> +      return redirect(routes.members)
Create a simple Access Denied Page and redirect user to that Page, for all the redirects

2023-03-02 11:52 UTC, richa-copods commented on app/models/result.server.ts
> +        status: 403,
Just status is sufficient, no need to send message and data field. For all the code blocks

2023-03-02 11:52 UTC, richa-copods commented on app/interface/Interface.tsx
> +export enum HTTP_CODE {
no need of this

2023-03-03 11:41 UTC, richa-copods requested changes

2023-03-03 11:41 UTC, richa-copods commented on app/routes/$workspaceId/results/groupByTests/$testId.tsx
> +    const candidatesCount = await getALLCandidatesOfTestCount(
Shouldn't it be `getCountofAllCandidatesOfTest` or at least `getAllCandidatesOfTestCount`

2023-03-03 11:41 UTC, richa-copods commented on app/routes/$workspaceId/results/groupByTests/index.tsx
> +    const totalTestCount = await getTotalTestCounts(
Can be named `getTotalTestsCount`

2023-03-03 11:41 UTC, richa-copods commented on public/locales/en/index.json
> +  "403": {
Name it to unauthorised

2023-03-03 11:41 UTC, richa-copods commented on app/routes/index.tsx
> +export const loader: LoaderFunction = async ({ request, params }) => {
Why have you destructured `params` when not being used?

2023-03-03 11:56 UTC, richa-copods requested changes

2023-03-03 11:56 UTC, richa-copods commented on app/routes/$workspaceId/results/groupByTests/index.tsx
> +    const testCount = await getALLCandidateTestsCount(
Shouldn't it be getCountofAllCandidatesOfTest or at least getAllCandidatesOfTestCount

2023-03-03 11:56 UTC, richa-copods commented on app/routes/$workspaceId/results/groupByTests/index.tsx
> +    const candidateTest = await getALLCandidateTests(
Shouldn't it be `getAllCandidatesOfTest`

2023-03-03 12:03 UTC, Dhruv-Copods commented on app/routes/index.tsx
> +export const loader: LoaderFunction = async ({ request, params }) => {
I had imported it while testing period, removing it

2023-03-03 12:27 UTC, richa-copods requested changes

2023-03-03 12:27 UTC, richa-copods commented on public/locales/en/index.json
> +    "error": "The route you tried to access was not authorized",
"You are not authorised to access this route"

2023-03-03 12:53 UTC, richa-copods requested changes

2023-03-03 12:53 UTC, richa-copods commented on public/locales/en/index.json
> +    "gotoDashboard": "GoTo Dashboard"
"Go to Dashboard"

2023-03-03 12:53 UTC, richa-copods commented on app/services/results.service.ts
>  export const getALLCandidateTestsCount = async (
Rename this

2023-03-03 12:53 UTC, richa-copods commented on app/services/results.service.ts
>  export const getALLCandidateTests = async (
Rename this

2023-03-03 12:53 UTC, richa-copods commented on public/locales/en/index.json
> +    "gotoDashboard": "GoTo Dashboard"
correct value of error for "404" also

2023-03-06 12:05 UTC, richa-copods approved these changes

2023-03-06 12:15 UTC, merged