[WIP] 740 apply access checks for candidate invite
copods/kela-quiz pull request #745
Opened 2023-03-02 14:17 UTC by Dhruv-Copods

2023-03-03 06:02 UTC, yash6102000 commented on app/routes/$workspaceId/assessments/$testId.tsx
> +    } catch (error: any) {
error don't have a type rather than any?

2023-03-03 06:02 UTC, yash6102000 commented on app/routes/$workspaceId/assessments/index.tsx
> +    } catch (error: any) {
same here

2023-03-06 12:41 UTC, richa-copods requested changes

2023-03-06 12:41 UTC, richa-copods commented on app/components/tests/InviteCandidatePopup.tsx
> +        actionData?.candidateInviteStatus === "candidateExamConstants.error"
Give proper name to the error

2023-03-06 12:41 UTC, richa-copods commented on app/models/candidate.server.ts
> +        status: 403,
Only status field is sufficient

2023-03-06 12:41 UTC, richa-copods commented on app/routes/$workspaceId/assessments/index.tsx
> +    if (action === "testDelete") {
Rename it to "deleteTest"

2023-03-06 12:41 UTC, richa-copods commented on app/routes/$workspaceId/assessments/index.tsx
> +      await formData.forEach((fd) => {
change "fd" to "data"

2023-03-09 06:10 UTC, anuragP04 approved these changes

2023-03-09 06:10 UTC, merged