708 update change password according to new design
copods/kela-quiz pull request #765
Opened 2023-03-06 10:21 UTC by ayushicopods

2023-03-09 12:39 UTC, yash6102000 commented on app/routes/$workspaceId.tsx
> +  // action will perform if match with specific formData
we are not performing any action here, we are assigning the specific value of formdata into variable

2023-03-09 12:39 UTC, yash6102000 commented on app/routes/$workspaceId/settings.tsx
>    useEffect(() => {
add this route into the route constant file

2023-03-10 16:42 UTC, ayushicopods commented on app/routes/$workspaceId.tsx
> +  // action will perform if match with specific formData
didn't get your point

2023-03-13 05:48 UTC, anuragP04 requested changes

2023-03-13 05:48 UTC, anuragP04 commented on app/routes/$workspaceId/settings.tsx
> +    if (location.pathname === "/settings")
pick route from routeConstants

2023-03-13 05:48 UTC, anuragP04 commented on app/components/settings/SettingTab.tsx
>    const tabs = [
don't remove this code, comment it out only

2023-03-13 10:52 UTC, yash6102000 commented on app/components/settings/ResetPassword.tsx
> +        {newPassword ? (
can we write it as newPassword&&

2023-03-15 04:39 UTC, Dhruv-Copods approved these changes

2023-03-15 05:08 UTC, yash6102000 requested changes

2023-03-15 05:08 UTC, yash6102000 commented on app/components/settings/ResetPassword.tsx
> +          {PasswordInputFieldProps.map((props) => {
please rename it as passwordInputFieldProps .....

2023-03-15 05:54 UTC, anuragP04 approved these changes

2023-03-15 05:54 UTC, merged