752 FE apply access checks for candidate invite
copods/kela-quiz pull request #782
Opened 2023-03-10 08:32 UTC by Dhruv-Copods

2023-03-10 13:29 UTC, richa-copods approved these changes

2023-03-13 07:03 UTC, anuragP04 requested changes

2023-03-13 07:03 UTC, anuragP04 commented on app/routes/$workspaceId/assessments/$testId.tsx
> +import { checkUserFeatureAuthorization } from "~/models/authorization.server"
.

2023-03-14 05:06 UTC, anuragP04 approved these changes

2023-03-14 05:06 UTC, merged