table is scrollable when data exceeds the viewport
copods/kela-quiz pull request #796
Opened 2023-03-14 13:04 UTC by ayushicopods

2023-03-15 04:42 UTC, Dhruv-Copods requested changes

2023-03-15 04:42 UTC, Dhruv-Copods commented on app/components/tests/TestList.tsx
> +          {/* </div> */}
Remove commented code

2023-03-17 09:38 UTC, Dhruv-Copods commented on app/components/common-components/TableComponent.tsx
> +        <div className="sticky bottom-0 z-0 rounded-b-2xl border  bg-white px-9 py-5 shadow">
remove extra spacing after word "border"

2023-03-17 09:46 UTC, Dhruv-Copods approved these changes

2023-03-20 08:46 UTC, anuragP04 approved these changes

2023-03-20 09:54 UTC, merged