[WIP]:832 develop feedback page on admin side
copods/kela-quiz pull request #837
Opened 2023-04-04 09:08 UTC by ayushicopods

2023-04-06 05:26 UTC, anuragP04 requested changes

2023-04-06 05:26 UTC, anuragP04 commented on app/components/feedback/FeedbackCard.tsx
> +      <div className="flex gap-4">
do we need this extra div here?

2023-04-06 05:26 UTC, anuragP04 commented on app/components/feedback/FeedbackContainer.tsx
> +  const candidatesFeedbackData = JSON.parse(useLoaderData())
why you are doing JSON.parse here?

2023-04-06 05:26 UTC, anuragP04 commented on app/interface/Interface.tsx
> +  candidate: {
can't we use candidate interface here?

2023-04-06 06:10 UTC, ayushicopods commented on app/interface/Interface.tsx
> +  candidate: {
because test name does not exist in Candidate interface

2023-04-06 06:10 UTC, ayushicopods commented on app/components/feedback/FeedbackContainer.tsx
> +  const candidatesFeedbackData = JSON.parse(useLoaderData())
because data is coming in stringify format

2023-04-11 08:12 UTC, anuragP04 approved these changes

2023-04-11 08:13 UTC, merged